import json, pathlib, hashlib
P=pathlib.Path(__file__).resolve().parent
B=P.parents[3]
def read(p): return json.loads(p.read_text())
def write(p,d): p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
old=read(P.parent.parent/'academy/chapter.json'); plan=read(P/'draft-beat-plan.json'); tr=read(P/'translations.json')
alts=[dict(zip(['ru','en','es'],s.split('|||'))) for s in (P/'alts.tsv').read_text().splitlines()]
assert len(alts)==49 and all(len(a)==3 for a in alts)
assert all(len(tr[x])==49 for x in ['ru','es'])
tr['ru'][47]='— До свидания! — попрощались дети. — До завтра, — ответила учительница.'
tr['es'][47]='«¡Adiós!», se despidieron los niños. «Hasta mañana», respondió la maestra.'
write(P/'translations.json',tr)
shots=plan['shots']
shots[0]['action']='Family pauses just outside the familiar closed cottage door before setting off; Mama securely cradles PomPom.'
shots[11]['action']='PinPin places the gifted pinecone onto a separate small tabletop tray; owl gathers pupils while Elder departs with staff in background.'
shots[22]['action']='Lulu returns the fifth cup to the tabletop tray and PinPin helps clear the bowl; the tray is moved away before the next construction view.'
shots[30]['action']='Mila brings the pinecone on its leaf toward the completed roof entrance; the cone is not yet centered beneath the roof.'
shots[30]['dialogue_en']='Mila brought their little guest to the roof. “In you go.”'
ver={6:2,12:4,22:2,28:2,29:3,34:2,35:2,43:2,46:2,47:2,48:2}
reuse={13:'scene-04-v2',14:'scene-05-v1',19:'scene-12-v1',37:'scene-24-v1',38:'scene-26-v1'}
seqs=[('morning','Утро и дорога в школу','Morning and the school path','La mañana y el camino a la escuela','Secure family carrying, dew joke, arrival and goodbye.'),('welcome','Гость в школе','A visitor at school','Una visita a la escuela','Playful Elder welcome gives the class one pinecone guest.'),('listening','Что слышно в лесу','Listening to the forest','Escuchar el bosque','Five pupils follow leaves, water and tapping sounds along safe paths.'),('snack','Хрустящий перерыв','A crunchy break','Una pausa crujiente','A visible tummy joke leads to shared snack and clearing the table.'),('building','Крыша для гостя','A roof for our guest','Un techo para nuestro invitado','All five children solve a physical problem together and test the result.'),('friends','Под старым дубом','Beneath the old oak','Bajo el viejo roble','After class, friendship and a gradual flower-crown craft.'),('pickup','Вместе после школы','Together after school','Juntos después de clase','Parents greet one another, admire the children’s work and leave together in daylight.')]
locks={
'morning':'Morning mist and dew; three family hedgehogs, PomPom is a carried baby, not a pupil; Mama supports him with both forearms. Closed familiar cottage door in01. Five distinct pupils introduced by06.',
'welcome':'Elder is a visiting guest, owl remains teacher. Gold spectacles worn; staff held08, parked09–11, retrieved12. The pinecone is a deliberately pretend pupil, one cone only.',
'listening':'Five pupils and owl on dry ground in whole-class frames; absent pupils in close cuts are off-camera. Pinecone stays on tabletop tray at school. Leaves → stream → snag, no river crossing.',
'snack':'Five pupils, five small cups and one shared apple bowl. Bruno makes the tummy sound. Exactly two forepaws per child; table is a plain workbench with separate mouse step.',
'building':'Same two pale blocks, one light bark slab and single cone on leaf. Roof fails with wide gap, blocks move closer, roof rests on both supports. Mila approaches entrance31; cone beneath roof32. One small cup makes rain. All five have a real task.',
'friends':'Early afternoon, five pupils at natural open-top oak root hollows, no cavern holes. Lulu gathers36, weaves open chain37, joins ring38, wears39 onward. Completed model remains on workbench.',
'pickup':'Sunny afternoon. Five children plus five parents and baby = eleven family actors; owl makes twelve in47–48. Close family shots omit others intentionally. Mama securely carries PomPom; Lulu keeps crown; final shared path has no night cottage ending.'}
cameras=[
'Child-eye medium-wide cottage departure pause','Wide low path view through morning mist','Low close view toward dew leaf and PinPin','Close reaction on PinPin’s nose and laughing carried baby','Wide school clearing arrival','Child-eye medium-wide five-pupil introduction','Medium family goodbye with reciprocal gaze','Wide arrival facing Elder and gathered class','Low medium-wide Elder bow toward pinecone','Child-height reaction close-up of Mila and Bruno','Medium Elder-to-PinPin handover','Low side medium view of reachable tabletop cone transfer','Close low upward listening portrait of Lulu','Upward canopy insert','Wide dry-bank path following the class','Child-height stream-bank listening group','Close Tutu and Mila reaction toward off-camera tapping','Wide walk toward pale snag','Close woodpecker on trunk','Bird-height downward look toward five grounded pupils and owl','Medium Bruno tummy reaction','Frontal child-height snack group','Medium tabletop clearing action','Medium-wide workbench kit introduction','Frontal workbench two-block placement','Close tabletop failed roof between wide supports','Medium reaction toward failed model and gap','Frontal two-support movement closer together','Frontal PinPin holds roof ready over braced supports','Child-height workbench placement with roof contacting both supports','Low tabletop view of Mila approaching model entrance','Frontal workbench water test','Low model-level dry-cone reveal','Frontal completed-model dialogue','Wide move toward oak open-top root seats','Medium oak-side daisy gathering','Close Lulu’s paws weaving a short chain','Medium close Lulu holding the completed ring','Medium close crown worn between Lulu’s ears','Wide five-friend quiet afternoon under oak','Wide approach of parents along school path','Wide family greeting at school edge','Medium family reunion and pointing toward workbench','Close rabbit mother and Lulu’s crown','Close Tutu and squirrel father','Medium two-pair mouse and badger reunion','Wide twelve-actor model demonstration','Wide twelve-actor school farewell','Wide sunny collective family departure']
oldby={s['src']:s for s in old['scenes']}
pick={int(s['id'][-2:]):s for s in read(P/'pickup-results.json')['selected']}
scenes=[]
for n,s in enumerate(shots,1):
 src=f'images/chapter-04-academy/revision-02/scenes/scene-{n:02}-v{ver.get(n,1)}.png'
 if n in reuse: src='images/chapter-04-academy/scenes/'+reuse[n]+'.png'
 if n==30: src='images/chapter-04-academy/revision-02/preproduction/model-handling-v2.png'
 meta=read((B/src).with_suffix('.json'))
 source={'kind':'new','blocks':[],'note':'User-requested adaptation: full school day, family life, new classmates and concrete cooperative learning; not an event narrated in original chapter04.'}
 if n in [35,40]: source={'kind':'expanded','blocks':[1],'note':'Original after-school oak gathering, expanded to five friends and retimed to early afternoon.'}
 if n in [36,37,38,39]: source={'kind':'expanded','blocks':[3],'note':'Original Lulu flower crown, unpacked into visible craft states; the new classmates remain nearby.'}
 if n in [41,43]: source={'kind':'expanded','blocks':[6],'note':'Original Mama pickup expanded to a sunny collective family pickup; PomPom and additional families are user-authorized additions.'}
 if n==49: source={'kind':'expanded','blocks':[7],'note':'Original homeward walk adapted into a collective sunny family departure, without another night-time home arrival.'}
 review=meta['review']
 for a,b in {'Creator review, independent root gate pending.': 'Creator review completed; independent root gate subsequently passed.', 'Root handling gate pending.': 'Root handling gate subsequently passed.', 'Creator review; root independent gate pending for proposed.': 'Creator review completed; independent root gate subsequently passed.', 'Creator review; root independent gate pending.': 'Creator review completed; independent root gate subsequently passed.', 'root/lead should check location impression against fixed site before selecting.': 'root subsequently accepted the location impression with this qualitative depth caveat.'}.items(): review=review.replace(a,b)
 if n<=41: review+=' Independent full-image selected-byte review passed in INDEPENDENT-REVIEW.md.'
 else: review+=' Independent root full-image review accepted; see pickup-results.json.'
 x={'id':s['id'],'sequence':s['sequence'],'src':src,'width':meta['width'],'height':meta['height'],'alt':alts[n-1],'text':{'ru':[tr['ru'][n-1]],'en':[s['dialogue_en']],'es':[tr['es'][n-1]]},'source':source,'camera':pick.get(n,{}).get('camera',cameras[n-1]),'continuity':locks[s['sequence']],'review':review,'reused':n in reuse or n==30,'provenance':str(pathlib.PurePosixPath(src).with_suffix('.json'))}
 before=s.get('before')
 if before:
  assert before in oldby,(n,before)
  x['before']=before;x['beforeText']=oldby[before]['text'];x['beforeNote']='Actual first-proposal passage and artwork; the revised passage may change staging, cast or its place in the expanded school day.'
  if n==21:
   x['beforeText']={lang:[p for q in old['scenes'][18:21] for p in q['text'][lang]] for lang in ['ru','en','es']}
   x['beforeNote']='Contextual replacement: the genuine three-image honey-jar anecdote from first-proposal scenes19–21 is shown against the new visible tummy joke. The before image is the middle frame of that earlier anecdote.'
  if n in [40,41,43,48,49]: x['beforeNote']='Contextual comparison with the actual first-proposal ending: time of day, family group and story moment have changed. This is not the same camera or an unchanged event.'
 if n in ver:
  x['rejectedAttempts']=[f'images/chapter-04-academy/revision-02/scenes/scene-{n:02}-v{v}.png' for v in range(1,ver[n]) if (B/f'images/chapter-04-academy/revision-02/scenes/scene-{n:02}-v{v}.png').exists()]
 scenes.append(x)
 s.update(status='selected and visually reviewed; proposed for user review',selected=src,camera=x['camera'],source=source,continuity=x['continuity'],review=x['review'],provenance=x['provenance'])
 s['cameraGate']='Relevant cast/site/prop reference accepted before dependent production; actual selected image independently reviewed.'
refs=[('family-carry-v1','Family carrying','Mama and baby handling front/profile; two-forearm support.'),('friend-families-v1','Lulu and Tutu families','Distinct mature rabbit mother and squirrel father with established children.'),('new-classmate-families-v2','Mila and Bruno families','Tiny mouse pair and badger pair; corrected relative mouse size.'),('class-five-v1','Five pupils and teacher','Working school scale authority; distinct child identities and owl teacher.'),('morning-home-v1','Morning cottage','Familiar closed green door, windows, chimney and unlit lantern.'),('morning-path-v1','Morning forest path','Walkable fern path, dew and soft mist.'),('academy-workbench-v2','Academy workbench','Plain four-legged table, separate broad mouse step, five cups and bowl.'),('model-states-v3','Model physical states','Same-width bark roof bridges genuinely narrowed support gap.'),('model-handling-v2','Five jobs at the model','Practical construction scale and five separated cooperative actions; also selected for scene30.'),('elder-welcome-v2','Elder school visit','Guest identity, corrected scale, glasses and parked staff.'),('oak-five-v1','Five friends at the oak','Natural open-top root seats, daytime light and pupil blocking.'),('pickup-families-v1','Family pickup clusters','Eleven actors arranged into five readable families, secure baby carry.')]
chapter={k:old[k] for k in ['schemaVersion','id','sourceChapter','status','title','cover','miniature']}
chapter['summary']={'ru':'От росы на утренней тропинке до встречи всех семей: Пин-Пин и друзья слушают лес, строят крышу для маленького гостя и делятся своим открытием.','en':'From dew on the morning path to a gathering of families: PinPin and his friends listen to the forest, build a roof for a little guest and share what they have made.','es':'Desde el rocío del camino hasta el encuentro de las familias: PinPin y sus amigos escuchan el bosque, construyen un techo para un pequeño invitado y comparten lo que han hecho.'}
chapter['preproduction']=[{'id':a,'title':b,'src':f'images/chapter-04-academy/revision-02/preproduction/{a}.png','description':c+' Root internally accepted after full-image review; still proposed for the user.'} for a,b,c in refs]
chapter['preproduction'] += [q for q in old['preproduction'] if q['id'] in ['site','pinpin-turnaround']]
chapter['sequences']=[{'id':a,'title':{'ru':b,'en':c,'es':d},'purpose':e} for a,b,c,d,e in seqs]
chapter['scenes']=scenes
chapter['editorialNotes']=['Revision02 is a complete 49-image proposal, not published. All first-proposal files remain intact.','Original chapter04 repeats its after-school passage; canonical first-pass blocks only are cited, zero-based. Full school day, Elder welcome, new classmates, construction task and collective daylight pickup are commissioned adaptations.','Mila and Bruno have concrete jobs; short dew, pretend-pinecone and tummy jokes replace the earlier failed honey-jar wordplay.','Ordinary later school morning: not asserted to be the promised next-dawn lesson from the Elder chapter.','Actual earlier text is retained beside genuine before images; contextual replacements are explicitly labeled.']
chapter['continuityNotes']=list(locks.values())+['Shared class lineup and handling plate control practical scale; coordinates in the bible are planning aids, not reconstructed calibrated geometry.','Minor generative variation remains: scene06 table depth is approximate; scene29 roof width/support gap differs modestly from scene30 while physically bridging both supports; family scale is qualitative. Scene34 model footprint was corrected.','Existing three-friend cover and textless miniature remain the chapter identity; the full revised cast appears in the story and preparation references.']
write(P/'chapter.json',chapter)
plan.update(status='complete selected proposal; user approval and publication pending',plannedBeats=49,quotaNote='49 meaningful story positions follow the required actions and transitions; this is not a fixed production quota.')
plan['gates']={'source':'Root passed complete38-chapter SOURCE-ARC.md','dialogueAndStructure':'Root internally accepted complete49-beat plan','castAndSites':'All relevant rendered reference regions internally accepted before dependent scenes','storyRendering':'All49 selected positions complete; independent full-image review passed','userApproval':'Pending; do not publish'}
write(P/'draft-beat-plan.json',plan)
write(P/'shot-plan.json',plan)
write(P/'selection.json',{'status':'proposed','scenes':[{'id':s['id'],'src':s['src'],'sha256':hashlib.sha256((B/s['src']).read_bytes()).hexdigest(),'provenance':s['provenance']} for s in scenes]})
(P/'dialogue-en.md').write_text('# Academy revision02 — selected English dialogue\n\nComplete 49-image proposal. All selected artwork rendered or explicitly reused and independently inspected; publication awaits user approval.\n\n'+'\n\n'.join(f"## {i:02} · {s['sequence']}\n\nVisible action: {s['action']}\n\n{s['dialogue_en']}" for i,s in enumerate(shots,1))+'\n')
(P/'source-adaptation-map.md').write_text('# Source and adaptation map\n\nRead with ../SOURCE-ARC.md. Original chapter04 repeats the after-school material; references below use zero-based canonical first-pass blocks, never the duplicate passage. The morning is a later ordinary school day, not the Elder’s promised dawn appointment.\n\n'+'\n'.join(f"- {s['id']}: **{s['source']['kind']}**, blocks {s['source']['blocks']}. {s['source']['note']}" for s in scenes)+'\n\nArtwork reuse is independent of source origin: listening inserts13/14/19 are new narrative adaptations even though their artwork already existed. Baby PomPom comes from user-approved published family canon rather than the original book.\n')
print('Saved complete chapter.json, shot-plan.json, selection.json and source map:',len(scenes),'scenes')
