import pathlib,json,hashlib,datetime
D=pathlib.Path(__file__).parent;R=next(p for p in D.parents if (p/'docs/storyboard').is_dir());SB=R/'docs/storyboard'
A={
2:('Papa supports PinPin on crouching Scooby beside a low mossy stone.','Папа поддерживает Пин-Пина на спине пригнувшегося Скуби рядом с низким мшистым камнем.','Papá sostiene a PinPin sobre Scooby agachado junto a una piedra baja cubierta de musgo.'),
3:('Papa stands on the stone and steadies PinPin, still astride Scooby.','Папа стоит на камне и придерживает Пин-Пина, который ещё сидит на Скуби.','Papá está de pie sobre la piedra y sostiene a PinPin, que aún monta a Scooby.'),
4:('PinPin lands with both feet on the stone while Papa supports him and Scooby watches.','Пин-Пин стоит обеими ножками на камне; Папа поддерживает его, а Скуби смотрит на них.','PinPin apoya los dos pies en la piedra mientras Papá lo sostiene y Scooby observa.'),
5:('Papa and PinPin walk holding paws, with attentive Scooby beside them.','Папа и Пин-Пин идут, держась за лапы; внимательный Скуби шагает рядом.','Papá y PinPin caminan de la pata, con Scooby atento a su lado.'),
6:('PinPin points at a dew drop hanging from a fern as Papa crouches beside him.','Пин-Пин показывает на каплю росы на папоротнике, а Папа приседает рядом.','PinPin señala una gota de rocío en un helecho mientras Papá se agacha a su lado.'),
7:('Papa and PinPin look together at a tiny rainbow inside a fern drop.','Папа и Пин-Пин вместе рассматривают крошечную радугу в капле на папоротнике.','Papá y PinPin miran juntos un diminuto arcoíris dentro de una gota del helecho.'),
8:('Papa holds PinPin’s paw as he steps over a low root; Scooby waits nearby.','Папа держит Пин-Пина за лапку, пока тот перешагивает низкий корень; Скуби ждёт рядом.','Papá sostiene la patita de PinPin al pasar sobre una raíz baja; Scooby espera cerca.'),
9:('PinPin holds a leafy twig aside while Papa bends beneath it, with Scooby watching.','Пин-Пин отводит веточку с листьями, пока Папа пригибается под ней; Скуби наблюдает.','PinPin aparta una ramita con hojas mientras Papá se agacha para pasar y Scooby observa.'),
10:('The three companions enter a sunny clearing beside a fallen log.','Трое друзей выходят на солнечную полянку рядом с упавшим бревном.','Los tres compañeros entran en un claro soleado junto a un tronco caído.'),
11:('Papa and PinPin spread a cream cloth beside their open picnic bag while Scooby rests nearby.','Папа и Пин-Пин расстилают светлую салфетку рядом с открытой сумкой для обеда; Скуби отдыхает поблизости.','Papá y PinPin extienden un paño claro junto a la bolsa abierta del almuerzo mientras Scooby descansa cerca.'),
12:('Papa breaks a roll in two as PinPin reaches to receive bread; apples, flask and nested wooden cup and bowl rest on the cloth.','Папа разламывает булочку надвое, а Пин-Пин протягивает лапки; на салфетке лежат яблоки, фляжка и деревянная чашка в миске.','Papá parte un panecillo mientras PinPin extiende las patas; sobre el paño hay manzanas, una cantimplora y una taza dentro de un cuenco de madera.'),
13:('PinPin hands Papa a whole apple while Scooby watches their picnic.','Пин-Пин передаёт Папе целое яблоко, а Скуби наблюдает за их обедом.','PinPin le entrega una manzana entera a Papá mientras Scooby observa el almuerzo.'),
14:('Papa pours water from a flask into the wooden cup that PinPin holds with both paws.','Папа наливает воду из фляжки в деревянную чашку, которую Пин-Пин держит двумя лапками.','Papá vierte agua de una cantimplora en la taza de madera que PinPin sostiene con las dos patas.'),
15:('PinPin steadies a water bowl on the grass while Scooby drinks and Papa watches.','Пин-Пин придерживает миску с водой на траве, пока Скуби пьёт, а Папа наблюдает.','PinPin sujeta un cuenco de agua sobre la hierba mientras Scooby bebe y Papá observa.'),
16:('PinPin nestles against Papa beside the log while Scooby sleeps; lunch remnants remain on the cloth.','Пин-Пин прижимается к Папе рядом с бревном, а Скуби спит; на салфетке остались крошки и надкушенные яблоки.','PinPin se acurruca contra Papá junto al tronco mientras Scooby duerme; quedan restos del almuerzo sobre el paño.'),
17:('Papa and PinPin fold the cream cloth together; their utensils are packed and Scooby waits.','Папа и Пин-Пин вместе складывают светлую салфетку; посуда убрана в сумку, а Скуби ждёт.','Papá y PinPin doblan juntos el paño claro; los utensilios están guardados y Scooby espera.'),
18:('Seen from behind, PinPin points to a root as the three continue walking; Papa wears the closed bag.','Вид со спины: Пин-Пин показывает на корень, пока трое продолжают путь; на Папе закрытая сумка.','Vistos desde atrás, PinPin señala una raíz mientras los tres siguen caminando; Papá lleva la bolsa cerrada.'),
19:('Papa and PinPin stand holding paws on a second broad stone with Scooby crouched beside them.','Папа и Пин-Пин стоят, держась за лапы, на другом широком камне; Скуби пригнулся рядом с ними.','Papá y PinPin están de la pata sobre otra piedra ancha, con Scooby agachado junto a ellos.'),
20:('Papa stands firmly on the stone and supports PinPin astride Scooby’s crouched back.','Папа твёрдо стоит на камне и придерживает Пин-Пина, сидящего на спине пригнувшегося Скуби.','Papá está firme sobre la piedra y sostiene a PinPin sentado sobre el lomo de Scooby agachado.'),
21:('Scooby stands on the broad stone with PinPin in front and Papa supporting him from behind.','Скуби стоит на широком камне; Пин-Пин сидит впереди, а Папа поддерживает его сзади.','Scooby está de pie sobre la piedra ancha, con PinPin delante y Papá sosteniéndolo desde atrás.'),
22:('Papa and PinPin arrive on Scooby at the huge tree with a doorway among roots; Papa carries the ochre bag.','Папа и Пин-Пин приезжают на Скуби к огромному дереву со входом между корнями; на Папе охристая сумка.','Papá y PinPin llegan sobre Scooby al enorme árbol con una entrada entre las raíces; Papá lleva la bolsa ocre.')}
p=D/'results.json';d=json.loads(p.read_text())
for s in d['parts'][0]['scenes']:
 n=int(s['id'].split('-')[-1])
 if n in A:s['alt']=dict(zip(['en','ru','es'],A[n]))
 if n==19:s['text']={'en':['After a while, PinPin’s steps grew smaller. They stopped together on another broad, low stone.'],'ru':['Через некоторое время шажки Пин-Пина стали короче. Они вместе остановились на другом широком низком камне.'],'es':['Al cabo de un rato, los pasos de PinPin se hicieron más cortitos. Se detuvieron juntos sobre otra piedra ancha y baja.']}
 if n==20:s['text']={'en':['Scooby turned and stayed low. Papa helped PinPin onto his warm back and kept one paw around him.'],'ru':['Скуби повернулся и остался лежать. Папа помог Пин-Пину сесть на тёплую спину и придержал его лапой.'],'es':['Scooby se giró y se quedó agachado. Papá ayudó a PinPin a sentarse sobre su lomo calentito y lo sostuvo con una pata.']}
 if n==17:s['text']={'en':['Papa put the cup and bowl away. Then they folded the cloth together, leaving the grass clean.'],'ru':['Папа убрал чашку и миску. Потом они вместе сложили салфетку, оставив траву чистой.'],'es':['Papá guardó la taza y el cuenco. Después doblaron el paño juntos y dejaron limpia la hierba.']}
 for lang in ['ru','en','es']:assert s['alt'][lang] and s['text'][lang]
 if not s.get('reused'):
  f=SB/s['src'];m=json.loads(f.with_suffix('.json').read_text());assert hashlib.sha256(f.read_bytes()).hexdigest()==m['sha256']==s['sha256'];assert m['status']=='ready'
d['status']='ready-for-root-review';p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
print('PASS:22 selected,21 generated; full RU/EN/ES alt+narration; selected SHA and metadata match')
