import json,pathlib
D=pathlib.Path(__file__).parent
rows=[
('A child’s view','They travelled between the tall trees. Scooby’s ears bobbed gently ahead.','Они ехали между высокими деревьями. Впереди тихонько покачивались уши Скуби.','Avanzaban entre los árboles altos. Delante, las orejas de Scooby se balanceaban suavemente.','T','child over-shoulder', [0.3,-.9,3.6], 'mounted', 'path', 'elder-r5-016'),
('A place to walk','“Can we walk here?” asked PinPin. Papa found a broad stone, and Scooby crouched beside it.','— А здесь можно пешком? — спросил Пин-Пин. Папа нашёл широкий камень, и Скуби пригнулся рядом.','—¿Podemos caminar aquí? —preguntó PinPin. Papá encontró una piedra ancha y Scooby se agachó a su lado.','S','wide low side',[-5,-5,1.1], 'stop', 'PinPin', None),
('Papa makes room','Papa stepped onto the stone. “I’ve got you.”','Папа встал на камень. — Я тебя держу.','Papá se puso de pie sobre la piedra. —Te tengo.','S','medium side contact',[-4,-3,1.4], 'papa-down', 'PinPin', None),
('Feet on the stone','PinPin slid into Papa’s arms. Soon his feet were on the stone too.','Пин-Пин скользнул в Папины лапы. Скоро и его ножки стояли на камне.','PinPin se deslizó entre los brazos de Papá. Pronto sus pies también estaban sobre la piedra.','S','close low landing',[-3,-3,.8], 'child-down', 'Papa', None),
('Three walkers','Papa took PinPin’s paw. Scooby padded alongside them.','Папа взял Пин-Пина за лапку. Скуби мягко шагал рядом.','Papá tomó la patita de PinPin. Scooby caminaba a su lado.','W','wide lateral movement',[-5,-4,1], 'walk', 'path', None),
('A tiny shining world','“Look, Papa!” A drop of water trembled at the tip of a fern.','— Папа, смотри! На кончике папоротника дрожала капля воды.','—¡Mira, Papá! Una gota de agua temblaba en la punta de un helecho.','W','child-eye close shared detail',[-2,-2,.6], 'droplet', 'fernDrop', None),
('A rainbow in a drop','Papa crouched beside him. They moved their heads, and the little drop flashed with colour.','Папа присел рядом. Они чуть повернули головы, и маленькая капля заиграла красками.','Papá se agachó a su lado. Movieron un poquito la cabeza y la gota brilló con colores.','W','reverse three-quarter close faces and fern',[-2,1,.65], 'droplet', 'fernDrop', None),
('Over the root','A root crossed the path. Papa offered his paw, and PinPin stepped over.','Поперёк тропинки лежал корень. Папа подал лапу, и Пин-Пин перешагнул через него.','Una raíz cruzaba el sendero. Papá le ofreció la pata y PinPin pasó por encima.','W','low hands feet root',[-3,-2,.6], 'root-step', 'Papa', None),
('PinPin helps too','“Now you, Papa!” PinPin held a low leafy twig aside while Papa ducked under it.','— Теперь ты, Папа! Пин-Пин отвёл в сторону тонкую веточку, а Папа пригнулся под ней.','—¡Ahora tú, Papá! PinPin apartó una ramita con hojas mientras Papá se agachaba para pasar.','W','medium child foreground father action',[-3,-3,1], 'twig-help', 'Papa', None),
('Their lunch place','Beyond the ferns was a sunny patch of grass. “Shall we have our lunch here?”','За папоротниками открылась солнечная полянка. — Пообедаем здесь?','Detrás de los helechos había un claro soleado. —¿Almorzamos aquí?','P','wide clearing reveal',[-5,-7,2], 'clearing', 'picnicLog', None),
('Together they spread the cloth','Papa opened the bag. PinPin caught the other corner of Mama’s cloth, and together they spread it on the grass.','Папа открыл сумку. Пин-Пин взял другой уголок Маминой салфетки, и они вместе расстелили её на траве.','Papá abrió la bolsa. PinPin tomó la otra punta del paño de Mamá y juntos lo extendieron sobre la hierba.','P','slightly high hands and cloth',[-3,-3,2.8], 'cloth', 'picnicCloth', None),
('Bread to share','Papa broke the bread in two. The soft middle was still lovely to smell.','Папа разломил хлеб надвое. Мягкая серединка так вкусно пахла!','Papá partió el pan en dos. ¡Qué bien olía la miga!','P','intimate bread action',[-2,-3,1.15], 'bread', 'bread', None),
('A piece for Papa','PinPin put an apple slice into Papa’s paw. “This one is for you.”','Пин-Пин положил дольку яблока в Папину лапу. — Это тебе.','PinPin puso una rodaja de manzana en la pata de Papá. —Esta es para ti.','P','medium two-shot clear handoff',[-3,-3,1], 'apple', 'Papa', None),
('A drink after walking','Papa poured some water into their little cup. PinPin held it carefully with both paws.','Папа налил воды в маленькую чашку. Пин-Пин осторожно держал её двумя лапками.','Papá sirvió agua en la tacita. PinPin la sujetó con cuidado entre las dos patas.','P','close pouring clear contacts',[-2,-2,.9], 'water', 'cup', None),
('Scooby has a drink','Scooby had his own bowl. PinPin set it on the grass, and Scooby lowered his nose to drink.','У Скуби была своя миска. Пин-Пин поставил её на траву, и Скуби опустил морду к воде.','Scooby tenía su propio cuenco. PinPin lo dejó sobre la hierba y Scooby bajó el hocico para beber.','P','low dog child bowl triangle',[2,-3,.65], 'dog-water', 'bowl', None),
('A little rest together','With lunch finished, PinPin leaned against Papa. Leaves whispered above them.','После обеда Пин-Пин прислонился к Папе. Над ними шелестели листья.','Después de comer, PinPin se apoyó en Papá. Las hojas susurraban sobre ellos.','P','wide quiet family cuddle',[-4,-5,1.1], 'rest', 'PinPin', None),
('Nothing left behind','They folded the cloth together. Papa put the cup and bowl away, and PinPin checked the grass.','Они вместе сложили салфетку. Папа убрал чашку и миску, а Пин-Пин оглядел траву.','Doblaron el paño juntos. Papá guardó la taza y el cuenco, y PinPin revisó la hierba.','P','top oblique packing',[-3,-3,2.6], 'pack', 'picnicCloth', None),
('Back along the path','They walked on. This time PinPin spotted the roots before Papa did.','Они пошли дальше. Теперь Пин-Пин замечал корни раньше Папы.','Siguieron caminando. Esta vez PinPin veía las raíces antes que Papá.','W','rear wide path leads onward',[-3,-5,1], 'walk-after', 'path', None),
('A ride for little feet','After a while, PinPin’s steps grew smaller. Papa led Scooby beside another low stone.','Через некоторое время шажки Пин-Пина стали короче. Папа подвёл Скуби к ещё одному низкому камню.','Al cabo de un rato, los pasos de PinPin se hicieron más cortitos. Papá llevó a Scooby junto a otra piedra baja.','S2','side full supports',[-4,-4,1], 'remount-ready', 'PinPin', None),
('Papa helps him up','Scooby crouched. Papa helped PinPin onto his warm back and kept one paw around him.','Скуби пригнулся. Папа помог Пин-Пину сесть на тёплую спину и придержал его лапой.','Scooby se agachó. Papá ayudó a PinPin a sentarse sobre su lomo calentito y lo sostuvo con una pata.','S2','medium contact from near flank',[-3,-3,1.2], 'child-up', 'PinPin', None),
('Together again','Papa settled behind him. “Comfortable?” “Yes!” Scooby stood up slowly.','Папа устроился сзади. — Удобно? — Да! Скуби медленно поднялся.','Papá se acomodó detrás. —¿Estás cómodo? —¡Sí! Scooby se levantó despacito.','S2','low three-quarter settled tandem',[-4,-3,1.2], 'mounted', 'PinPin', None),
('The great tree','Then the trees opened. On Burrow Hill stood a great old tree, with a little doorway among its roots.','И вот деревья расступились. На Холме Нор стояло огромное старое дерево с маленьким входом между корнями.','Entonces los árboles se abrieron. En la Colina de las Madrigueras se alzaba un árbol enorme y antiguo, con una puertecita entre sus raíces.','E','low wide destination reveal',[-3,-9,.8], 'mounted', 'threshold', 'elder-r5-017')]
def actor(n,pos,pose,eye,contact):return {'name':n,'positionXYZ':pos,'bodyFacingTarget':eye,'headFacingTarget':eye,'eyeTarget':eye,'pose':pose,'limbsContactSupport':contact,'visibility':'visible unless specified by purposeful crop'}
scenes=[]
for i,(label,en,ru,es,frame,framing,cam,state,gaze,prev) in enumerate(rows,1):
 mounted=state in ['mounted','stop']; picnic=frame=='P'; childpos=[-.6,0,0]; papapos=[.7,0,0]; dogpos=[2,1,0]
 if mounted: dogpos=[0,0,0];childpos=[0,.4,2.7 if state=='mounted' else 1.3];papapos=[0,-.4,childpos[2]]
 if picnic: childpos=[-.7,-.7,0];papapos=[.7,.4,0];dogpos=[2.5,.5,0]
 actors=[actor('Papa',papapos,'seated behind child' if mounted else state,gaze,'One forearm supports child lower torso, other paw braces dog back' if mounted else 'two hindfeet or seated hips on firm ground; exact paw action follows shot action'),actor('PinPin',childpos,'seated astride behind withers' if mounted else state,gaze,'thighs straddle; two forepaws on dog shoulder' if mounted else 'grounded child; exact paw action follows shot action'),actor('Scooby',dogpos,'gentle walking' if mounted and state!='stop' else 'resting/crouched' if picnic or state=='stop' else 'grounded attentive companion', 'path' if mounted else 'PinPin','four anatomical limbs; no saddle/reins; visible paws contact ground, hidden limbs not certified')]
 for a in actors:
  if a['name']==gaze:a['eyeTarget']='PinPin' if a['name']=='Papa' else 'Papa';a['headFacingTarget']=a['eyeTarget']
 scene={'id':f'elder-r6-forest-{i:03}','sequence':'forest-path','label':label,'text':{'en':[en],'ru':[ru],'es':[es]},'previousID':prev,'source':{'kind':'expanded' if i==22 else 'new','blocks':[0] if i==22 else [],'note':'User-authorized family forest outing adaptation; only destination Burrow Hill derives directly from original chapter02 block0. No invented magic event.'},'state':state,'cameraTransform':{'schemaVersion':1,'purpose':label+': '+en,'frameId':frame,'units':'Approximate PinPin standing heights; illustrative, not measured geometry.','camera':{'positionXYZ':cam,'targetXYZ':[0,0,1],'height':cam[2],'framing':framing,'fieldOfViewDegrees':65 if 'wide' in framing else 48,'axisSide':'negative X unless named reverse; neutral establishing shot precedes new region'},'actors':actors,'staticLandmarks':{'path':[0,6,0],'fernDrop':[-1,1,.65],'picnicLog':[0,1,.6],'picnicCloth':[0,0,0],'bread':[0,0,.2],'cup':[.1,-.1,.2],'bowl':[2,-.5,0],'threshold':[0,8,0],'stone':[-1,0,.35]},'objectStates':{'before':'Carrier continuity pending root choice; picnic states are established in bible.','after':state},'transition':{'previous':rows[i-2][0] if i>1 else 'supported departure from family home','next':rows[i][0] if i<len(rows) else 'arrival and familiar Elder welcome','reason':label}},'status':'planned'}
 scenes.append(scene)
plan={'schemaVersion':1,'status':'planned awaiting storage/prop approval','part':{'id':'forest-path','title':{'en':'Through the Forest','ru':'Через лес','es':'Por el bosque'},'summary':{'en':'Papa, PinPin and Scooby walk, discover little wonders and share lunch before reaching the Elder’s tree.','ru':'Папа, Пин-Пин и Скуби идут через лес, замечают маленькие чудеса и обедают на полянке по дороге к Старейшине.','es':'Papá, PinPin y Scooby caminan, descubren pequeñas maravillas y almuerzan juntos antes de llegar al árbol del anciano.'}},'scenes':scenes}
(D/'story-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
(D/'REPORT.md').write_text('# Forest lane revision06\n\n22-beat full trilingual story plan persisted. Original chapter01/02 and source map read. All new forest/picnic business explicitly adaptation. Family-style-v3, papa-style-v1, home-51-v1 actually viewed. Storage and carrier decision pending. No image generation yet.\n\nCharacter reference review: Papa cream adult face/readable iris; no glasses; child distinctly smaller; dog ~2.7 child heights at shoulder. Family reference includes unwanted cast which must not enter forest scene. Papa isolated study identity only, dark background not lighting authority. Home51 authoritative luminous illustrated treatment, Elder glasses NOT transferable.\n')
