import json,pathlib,sys
D=pathlib.Path(__file__).parent
S={
2:'Full side view of Scooby crouched low beside broad stone at LEFT of path. Both riders still seated: child directly behind shoulders, Papa behind, mature hazel face angled down to child asking to walk. Dog turns attentive eyes back. Papa right-hip bag behind him. Two slim white birches behind stone, fern right. Child near hindleg hangs beside shoulder, never both feet on top. Clear four dog limbs with natural far occlusions.',
3:'Move camera closer to near flank. Papa has dismounted onto broad low stone beside Scooby. BOTH Papa hindfeet planted on stone. Papa one forepaw steadies child lower torso, other rests dog back. Child remains seated astride shoulder and watches Papa. Dog remains belly-low, looks at Papa. Satchel remains on Papa right hip. This is intermediate dismount contact, not everyone already walking.',
4:'Close low landing image: Papa stands on stone and supports PinPin around lower torso with BOTH forepaws as child hindfeet reach the SAME stone. Child two small paws rest Papa forearms. Dog shoulder/head to right watches, cropped body acceptable. Child is now off dog; no extra feet on its back. Papa bag follows right hip, not child.',
5:'Wide lateral forest walking scene. Papa and PinPin walk side by side holding one pair of paws between them, the other paws free. Child steps independently on firm path. Scooby on far side behind them, full four leg gentle gait and curled tail, head inclines toward child. Bag right hip. This is walking rather than riding; tiny hedgehogs relative to dog shoulder. Layer foreground ferns and tall tree depth.',
6:'Child-eye close discovery: PinPin at left points one paw toward a clear dew drop on tip of fern at right without touching. Papa crouches behind/left close enough for shared attention, two eyes directed exactly to droplet, no self-gazing. Dog deliberately offscreen right. Path still background. Soft sun sparkles in drop, no fantasy glow or rainbow beam. Papa strap visible if chest shown.',
7:'Reverse three-quarter close shared discovery from slightly farther along path. Papa and PinPin heads side by side at child level, both tilt a little to see a tiny natural spectrum in the same fern-tip drop in foreground. Drop remains hanging. Papa points nowhere; two paws grounded or on knees, child two paws near belly. Dog offscreen. This is an intimate reciprocal activity, no giant magical rainbow or spell.',
8:'Very low side contact frame on flat forest path: a modest root only 15% child height crosses ground. Papa already beyond root offers one paw, PinPin holds it and steps ONE hindfoot over root, other hindfoot behind grounded. Papa other paw relaxed and two feet grounded. Scooby stands beyond waiting, dog legs may frame upper background, no trampling. Satchel right hip. Readable helping hands and feet, no leap or cliff.',
9:'Medium dynamic reciprocal help. A thin supple leafy twig projects across path from LEFT, its leafy end at Papa head height. PinPin at left holds LIGHT twig gently aside with one paw within reachable height, standing balanced on both feet. Papa ducks head under with amused smile looking toward child, knees bent and free paws for balance, satchel right hip. Scooby beyond on right watches. Do not let child lift a log or huge branch.',
10:'Wide reveal entering picnic clearing. Subjects relatively small front-left: Papa and child walking hand in paw, Scooby on right. Their attention leads toward flat sunny grass in front of horizontal low fallen log, double-trunk birch behind LEFT end, fern clump RIGHT. Path exits back right. Papa carries closed satchel at right hip. Warm midday light upperleft, inviting resting place, no food already laid out.',
11:'Slightly high view of genuine teamwork on grass in front of log: Papa kneels at upperright and PinPin lowerleft, each holds two neighboring corners of one small cream linen cloth with muted ochre hem, spreading it between them. Satchel OPEN on ground at log right, strap slack beside it, Papa no longer wears bag. Food still partly visible inside bag: bread parcel, two small whole apples, stoppered water flask; wooden cup nested in shallow bowl. Scooby lies to right out of the way, watching cloth. Four distinct forepaws total on cloth, no duplication.',
12:'Close intimate bread-breaking two-shot on same picnic cloth. Papa seated upperright in front of log, child lowerleft. Papa holds one small bread roll in BOTH paws, pulling into two halves with soft crumb showing. Child paws poised to receive one, looking at bread, Papa gaze child/bread. Open bag on ground behind Papa right, no strap across chest while bag grounded. Two small whole apples, corked water flask and nested cup/bowl on cloth. Scooby partial behindright or outside crop. No knife.',
13:'Medium clear handoff: PinPin seated lowerleft holds ONE small whole red-yellow apple in one paw and places it into Papa open paw upperright. Their pupils connect warmly. Second apple remains on cloth alongside two bread portions and stoppered flask. Papa other paw rests on lap. Satchel stays on ground by log right. Scooby lies right attentive to child, no begging bread. No sliced apples or knife.',
14:'Close water-pouring action on picnic cloth: Papa upperright holds small unstoppered plain water flask with both forepaws and pours modest visible stream into a small wooden cup that PinPin lowerleft steadies with BOTH forepaws ON cloth. Cup not floating, no spill. Stopper beside flask location. Shallow dog bowl near cloth right edge. Bag grounded by log right, no chest strap. Bread/apple remnants visible, no new food. Dog offscreen right. Faces may be partly cropped to give hands and water clarity.',
15:'Low dog-child interaction from grass height: PinPin kneels at right edge of picnic cloth, both paws touch shallow wooden bowl rim as he sets bowl FULL OF WATER firmly onto grass in front of Scooby. Dog lies with two front paws either side behind bowl, lowers cream muzzle to drink with soft attentive eyes. Papa seated behind on left with water flask on cloth, watches child, bag ground by log right. Dog two hindlimbs naturally tucked, one tail. No extra dog or bowl, no giant cup.',
16:'Quiet wide afternoon rest in established clearing. Papa seated against front of low fallen log, child leaning into his side with cheek to Papa chest and one arm of Papa gently around child. Both relaxed open or softly lowered eyes, no secretive whisper. Scooby asleep to right curled naturally, bowl beside front paws. Cloth foreground carries only finished lunch remnants, small cup and stopped flask; bag ground log right. Doublebirch left, fern right, dappled sunlight. This is physical cuddle and rest, not portrait lineup.',
17:'Oblique slightly high cleanup: Papa and PinPin kneeling opposite corners jointly fold the SAME cream cloth smaller over the now-cleared grass. Satchel open ground by log right, visible wooden cup nested in shallow wooden bowl and corked flask inside; no spare bowl on grass. No more bread or apples scattered. Scooby now sits to right looking at them. No bag strap on Papa while bag grounded. Ground after picnic clean. Two paws each holding cloth natural.',
18:'Rear wide view walking away from picnic clearing along forest path. Papa again wears CLOSED ochre satchel right hip, strap left shoulder. Child a small step ahead points out modest root on path with one paw, Papa follows attentively, Scooby walks beside them on right. Everyone walking, no rider. Low picnic log recedes behind through trees, no cloth/bowl left there. Warm midday forest depth, camera gives sense of going onward.',
19:'Side full view at SECOND low broad stone beside path. Papa and tired PinPin stand together on stone beside Scooby, who has crouched belly low. Papa holds child paw and looks down warmly, child small relaxed shoulders, not distressed. Double birch behind stone, no Elder house yet. Closed satchel right hip. Dog looks back attentive, four legs plausible crouch. This establishes remount support before child boards.',
20:'Medium contact from dog near flank. Papa BOTH feet planted on broad stone, one arm around child lower torso while child sits astride Scooby just behind withers, near hindleg hangs down flank, farleg occluded, two small forepaws on shoulder. Papa otherpaw braces dog back. Dog crouched stationary ON SAME BROAD FLAT STONE AS PAPA, softly watches child. Satchel behind Papa right hip away from child. No airborne child or Papa, no standing on dog.',
21:'Low three-quarter complete tandem after boarding. Papa now seated astride Scooby behind child, one forearm across child lower torso, otherpaw braces back. Child straddles behind withers with two forepaws shoulder and gaze up to Papa responding. Papa looks down into child eyes. Scooby has slowly risen on four grounded legs ON TOP OF same broad flat stone, looks along path. Closed bag behind Papa right hip with strap over leftshoulder. Size child distinctly smaller adult; Papa notdoghybrid, no spectacles.',
22:'EDIT target first reference, preserve exact monumental tree/root portal, staff-boulder LEFT, fern RIGHT, path, sunlight, camera, Scooby and two riders, all faces/limbs/physical contacts. Add ONLY the approved small muted ochre cloth satchel to Papa RIGHT hip near camera and correct single strap from HIS LEFT shoulder diagonally across chest/back route to bag. Satchel attached to Papa, not dog. On this rearthreequarter view bag visible beside Papa lower right flank, no food spilling; softstraps follow body naturally, do not cut through quills or child. Preserve all other pixels as closely as possible. Afternoon warm daylight already compatible.'
}
STYLE='''Use case: illustration-story. ONE full-bleed landscape 3:2 finished children's-book illustration, no text or panels. PRIMARY STYLE: luminous soft expressive animated forms consistent with approved study, cream face planes, readable hazel/amber iris around separate pupil, broad gentle lids, grouped sculpted short fur and quills. Mature Papa 1.6 times child height; dog shoulder 2.7 child heights. CRITICAL SCALE: when standing the dog shoulder is clearly HIGHER than Papa head, and its head is much higher; Papa reaches only dog shoulder lower edge. Never shrink Scooby to child-size companion. Papa hedgehog cream face, elongated mature muzzle and robust body, tipped brown-grey quills, NO glasses. PinPin small chestnut child. Scooby brown/brindle, white chest bib, cream-grey muzzle, short folded ears, curled tail, attentive meaningful gaze. All animals unclothed; ochre cloth bag is a carried prop, not clothing. No photoreal headshot/PBR materials, black button eyes, masks, saddles/reins/collars or humans. Exactly Papa, PinPin, Scooby; no Mama/baby/Elder copied from identity reference. Two forepaws and two hindlegs per hedgehog, four dog legs and one tail; occluded limbs stay hidden. Natural contact and believable support. Daylight only. No captions, borders, watermarks, montage, arrows or labels.\n'''
if __name__=='__main__':
 n=int(sys.argv[1]);v=int(sys.argv[2]) if len(sys.argv)>2 else 1;plan=json.loads((D/'story-plan.json').read_text());s=plan['scenes'][n-1];refs=[]
 if n==22:refs.append({'path':'images/chapter-02-expanded/revision-05/scenes/scene-017-v2.png','role':'EDIT TARGET: preserve destination scene, add approved satchel on Papa only'})
 refs.extend([{'path':'images/chapter-02-expanded/revision-06/forest/preproduction/satchel-contact-v2.png','role':'AUTHORITATIVE Papa/PinPin/Scooby identities and soft style, correct satchel contact/scale. NOT a montage layout to copy.'},{'path':'images/chapter-02-expanded/revision-06/forest/preproduction/environments-v1.png','role':'Geography only. Use left stop/path for walking, right clearing for picnic. Not a split-panel layout; output ONE scene.'},{'path':'images/chapter-02-expanded/revision-05/preproduction/papa-style-v1.png','role':'Papa face/identity only, never transfer darkbackground or isolate as portrait.'}])
 if n in (20,21): refs.insert(0,{'path':'images/chapter-02-expanded/revision-06/forest/scene-019-v1.png','role':'PRIMARY GEOGRAPHY AUTHORITY: second broad flat stone with Papa, child AND Scooby all supported ON TOP, not beside. Preserve same rock width/height, dog body toward left and tail at rear-right. Change only boarding stage/camera as described.'})
 if 12 <= n <= 17: refs.append({'path':'images/chapter-02-expanded/revision-06/forest/scene-011-v1.png','role':'Picnic geography and PROP authority: plain cream linen cloth with ochre edge, NO CHECKERBOARD/STRIPES. Same flask, cup, two apples and grounded open satchel. Do not copy spreading action.'})
 prompt=STYLE+'REFERENCE ROLES: '+ '; '.join('Image '+str(i+1)+': '+r['role'] for i,r in enumerate(refs))+'\nSHOT ACTION AND CAMERA: '+S[n]+'\nPERSISTED CAMERA/ACTOR RECORD (approximate art direction, not labels): '+json.dumps(s['cameraTransform'],ensure_ascii=False)
 spec={'id':s['id'],'stem':f'scene-{n:03}-v{v}','version':v,'references':refs,'mode':'edit' if n==22 else 'generate','prompt':prompt,'cameraTransform':s['cameraTransform']}
 (D/f'spec-{n:03}-v{v}.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
 print(str(D/f'spec-{n:03}-v{v}.json'))
