import json,hashlib,subprocess,sys,shutil
from pathlib import Path
r=Path(__file__).resolve().parents[2]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,x):p.write_text(json.dumps(x,indent=2)+"\n")
notes={16:"Broad trailer and tractor alignment is usable. Road texture and foliage change scale/softness across the source boundary, especially lower left. Rear tree and stream remain readable; repaired pole centers are coherent, with stretched and soft outer overlap bands.",17:"Wide subject coverage preserves the tractor silhouette. Foreground foliage transitions remain visible in downward oblique views, with a soft band around the source and sharper generated rocks. Rear stream and trees are coherent; outer pole foliage remains stretched.",18:"Source machinery remains intact. A conspicuous foreground foliage softness/position transition remains below the tractor and appears across downward oblique views. The repaired down center has coherent stones and leaf litter; pole overlap bands remain soft/stretched.",19:"Source tractor and trailer remain intact. Foreground fern and road texture change across the lower source edge; some tree boundaries and pole overlaps remain soft/stretched. Rear tree/stream and the down-center leaf litter are coherent."}
rows=[]
for i in range(16,20):
 d=r/"stops"/f"stop-{i:02d}";camera=json.loads((d/"camera-v1.json").read_text());rel=lambda p:str(p.relative_to(r))
 for k in ["up","down"]:
  prompt=d/f"{k}-prompt.txt";expected=(r/"stops/stop-06"/f"{k}-prompt.txt").read_bytes()
  if prompt.exists():assert prompt.read_bytes()==expected
  else:prompt.write_bytes(expected)
  subprocess.run([sys.executable,str(r/"record_13_23.py"),"--directory",str(d),"--output",f"{k}-v1.png","--prompt",prompt.name,"--record",f"{k}-generation.json","--original","Unmodified returned PNG; invocation mapping verified by coordinator from original tool-call record at2026-09-24T23:04:45.857Z","--inputs",json.dumps([{"path":f"{k}-input-v2.png","role":"Exact registered 110-degree pole view, extracted after rear repair; sole image-generation input."}])],check=True,stdout=subprocess.DEVNULL)
 source=sha(d/"source-display.png");assert source==json.loads((d/"source-display.json").read_text())["output"]["sha256"]
 ex=d/"source-locked-exports-v1";manifest=json.loads((ex/"exports-v1.json").read_text());assert manifest["verification"]["pass"] and manifest["verification"]["allSixAtlasTilesEqualFaceFiles"]
 for out in manifest["outputs"]:assert sha(Path(out["path"]))==out["sha256"]
 review=f"# {d.name} source-lock review\n\nStatus: experimental, visually reviewed prototype; no claim of measured geometry or seamless art.\n\nInspected anchored entry, yaw +/-30 and +/-60 degrees, up/down obliques, all six cardinal directions, rear-up/down, and front-down contacts. {notes[i]}\n\nThe original source-display.png hash remains {source}. The selected opening camera, sourceCamera and sourceAnchor.camera are identical to the saved fit-v1 camera. Native source pixels and accepted motion blur remain unchanged. The baked sphere resamples the native source, while runtime retains it separately. No image generation, blur filtering or art edits occurred in this export lane.\n\nBackground: panorama-assembled-v1.png, assembled from hash-pinned base/rear/up/down masters at3072x1536. Source-locked sphere: panorama-source-locked-v1.png at4096x2048. Cube atlas: source-locked-exports-v1/cube-atlas-v1.png at3072x2048, with six1024px faces. All twelve same-ray adjacency checks pass with zero error and six atlas tiles equal their face files. This verifies projection, not artistic continuity.\n\nforward.png shows generated background only; forward-source-locked.png shows the anchored opening. Review contacts: review-final-v1/directions.jpg and review-edges-final-v1/directions.jpg. Browser switching/full24 review belongs to A and is separate from this deterministic contact review.\n"
 (d/"source-lock-review.md").write_text(review);(d/"review.md").write_text(review)
 s={"schemaVersion":1,"id":d.name,"status":"reviewed","sourceLockStatus":"experimental","panorama":rel(d/"panorama-assembled-v1.png"),"camera":camera,"sourceCamera":camera,"authoredGuideCamera":{"yaw":0,"pitch":0,"fov":65},"sourceAnchor":{"asset":rel(d/"source-display.png"),"camera":camera,"aspect":16/9,"featherStart":.94},"anchoredPanorama":rel(d/"panorama-source-locked-v1.png"),"anchoredCube":rel(ex/"cube-atlas-v1.png"),"anchoredExports":rel(ex/"exports-v1.json"),"exports":rel(ex/"exports-v1.json"),"forward":rel(d/"forward-source-locked.png"),"backgroundForward":rel(d/"forward.png"),"stack":rel(d/"selected-stack.json"),"prompt":rel(d/"panorama-prompt.txt"),"record":rel(d/"panorama-generation.json"),"review":rel(d/"review.md"),"sourceLockReview":rel(d/"source-lock-review.md"),"panoramaSha256":sha(d/"panorama-assembled-v1.png"),"forwardSha256":sha(d/"forward-source-locked.png")}
 write(d/"selected.json",s);rows.append(f"| {i} | {camera[chr(102)+chr(111)+chr(118)]:.4f} | experimental | 12/12, six tiles equal |")
(r/"FOUR-FINAL-REVIEW.md").write_text("# Stops16–19 final export review\n\nAll four selected.json descriptors now reference real source-locked spheres, cube atlases, six faces and export provenance. No generation was run. Native source-display images were hash-checked unchanged, and camera/sourceCamera/sourceAnchor.camera match.\n\n| Stop | Fitted vertical FOV | Source-lock status | Projection checks |\n|---|---:|---|---|\n"+"\n".join(rows)+"\n\nAll anchored cardinal and source-boundary contact sheets inspected. Remaining scenery/foreground and pole overlap joins are disclosed in each source-lock-review.md. Stop18 has the most visible lower-source foliage transition. Motion blur is preserved as requested. The geometry is an experimental inferred continuation, not measured reconstruction. Browser24 QA remains with A.\n\nStop19 down-v1.png recovered from the complete existing image-generation master: all2160000bytes of the truncated transfer matched its prefix; complete2791189byte PNG validated and SHA256 f7b94067b6ab21b55799bbbe10a3c16bcb3797809ea5f3d130565d2bc0cf4156. All eight pole-generation records use the actual up/down-input-v2.png and exact stop06 prompts, verified by coordinator against original2026-09-24T23:04:45.857Z invocation. Private logs excluded.\n")
print("FOUR SELECTED READY")
