#!/usr/bin/env python3
"""Triangular monotone inverse projection. Every color comes from generated V2."""
import argparse,hashlib,json,pathlib,math
import cv2,numpy as np
from scipy.interpolate import PchipInterpolator
ap=argparse.ArgumentParser();ap.add_argument('--registration',required=True);ap.add_argument('--out',required=True);ap.add_argument('--width',type=int,default=3072);a=ap.parse_args();out=pathlib.Path(a.out);out.mkdir(parents=True,exist_ok=True);r=json.loads(pathlib.Path(a.registration).read_text());pano=cv2.imread(r['panorama']['path']);sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();assert sha(r['panorama']['path'])==r['panorama']['sha256'];H=np.array(r['matrixRawXYToFlatPanoramaXY']);rw,rh=r['reference']['width'],r['reference']['height'];aspect=rw/rh;t=math.tan(math.radians(22.5));half=math.atan(t*aspect)
def hxy(x,y):
 den=H[2,0]*x+H[2,1]*y+H[2,2];return (H[0,0]*x+H[0,1]*y+H[0,2])/den,(H[1,0]*x+H[1,1]*y+H[1,2])/den
def min_derivative(p):
 c=p.c;dt=np.diff(p.x);vals=[c[2],3*c[0]*dt*dt+2*c[1]*dt+c[2]]
 z=np.divide(-c[1],3*c[0],out=np.full_like(c[0],np.nan),where=abs(c[0])>1e-20);ok=(z>0)&(z<dt);q=3*c[0]*z*z+2*c[1]*z+c[2];vals.append(np.where(ok,q,np.inf));return float(np.nanmin(np.stack(vals)))
angles=np.linspace(-half,half,65);rawx=(np.tan(angles)/(t*aspect)+1)*rw/2-.5;px,_=hxy(rawx,np.full_like(rawx,(rh-1)/2));sangles=((px+.5)/pano.shape[1]-.5)*2*np.pi;tail=np.radians([160,165,170,175,180]);tx=np.r_[-tail[::-1],angles,tail];sx=np.r_[-tail[::-1],sangles,tail];assert np.all(np.diff(sx)>0);gx=PchipInterpolator(tx,sx);minx=min_derivative(gx);assert minx>0
w=a.width;hh=w//2;u=(np.arange(w)+.5)/w;v=(np.arange(hh)+.5)/hh;theta=(u-.5)*2*np.pi;mappedu=gx(theta)/(2*np.pi)+.5;mapv=np.empty((hh,w),np.float32);miny=1.;rawys=np.linspace(-.5,rh-.5,49)
for i,angle in enumerate(theta):
 ac=float(np.clip(angle,-half,half));rx=(math.tan(ac)/(t*aspect)+1)*rw/2-.5;py=(1-2*(rawys+.5)/rh)*t;targetv=.5-np.arctan(py*math.cos(ac))/np.pi;_,sy=hxy(np.full_like(rawys,rx),rawys);sourcev=(sy+.5)/pano.shape[0];tv=np.r_[0,.025,.05,.075,targetv,.925,.95,.975,1];sv=np.r_[0,.025,.05,.075,sourcev,.925,.95,.975,1];assert np.all(np.diff(tv)>0) and np.all(np.diff(sv)>0);gy=PchipInterpolator(tv,sv);q=np.clip((abs(angle)-half)/(math.radians(165)-half),0,1);weight=1-q*q*(3-2*q);miny=min(miny,(1-weight)+weight*min_derivative(gy));mapv[:,i]=(1-weight)*v+weight*gy(v)
assert miny>0;mapu=np.broadcast_to(mappedu,(hh,w)).astype(np.float32);assert np.all(np.diff(mapu,axis=1)>0) and np.all(np.diff(mapv,axis=0)>0)
# Polar blend occurs only where latitude mapping is exactly identity, so its cross term cannot fold the map.
polar_distance=np.minimum(v,1-v);pw=np.clip((polar_distance-.025)/.025,0,1);pw=pw*pw*(3-2*pw);original_u=np.broadcast_to(u,(hh,w)).astype(np.float32);mapu=(original_u+pw[:,None]*(mapu-original_u)).astype(np.float32);assert np.all(np.diff(mapu,axis=1)>0)
result=cv2.remap(pano,mapu*pano.shape[1]-.5,mapv*pano.shape[0]-.5,cv2.INTER_LINEAR,borderMode=cv2.BORDER_WRAP);name='panorama-projection-v2.png';cv2.imwrite(str(out/name),result)
# Exact coordinate identity near rear and true pole caps; compare against same-resolution identity sampling.
baseu=np.broadcast_to(u,(hh,w)).astype(np.float32);basev=np.broadcast_to(v[:,None],(hh,w)).astype(np.float32);identity=cv2.remap(pano,baseu*pano.shape[1]-.5,basev*pano.shape[0]-.5,cv2.INTER_LINEAR,borderMode=cv2.BORDER_WRAP);rear=np.broadcast_to((abs(theta)>=math.radians(165)),(hh,w));poles=np.broadcast_to(((v<=.05)|(v>=.95))[:,None],(hh,w));fixed=rear|poles
# Longitude compression necessarily also affects polar azimuth, but true pole latitude remains fixed.
check={'positiveJacobianLowerBound':minx*miny,'minimumLongitudeDerivative':minx,'minimumLatitudeDerivative':miny,'longitudeStrictlyIncreasingEveryOutputRow':bool(np.all(np.diff(mapu,axis=1)>0)),'latitudeStrictlyIncreasingEveryOutputColumn':bool(np.all(np.diff(mapv,axis=0)>0)),'rearPixelMaxDiffVsIdentity':int(np.max(abs(result[rear].astype(int)-identity[rear].astype(int)))),'polarLatitudeCoordinateMaxError':float(np.max(abs(mapv[poles]-basev[poles]))),'rearUVMaxError':float(max(np.max(abs(mapu[rear]-baseu[rear])),np.max(abs(mapv[rear]-basev[rear]))))};assert check['rearPixelMaxDiffVsIdentity']==0
truecaps=np.broadcast_to(((v<=.025)|(v>=.975))[:,None],(hh,w));check['polarCapPixelMaxDiffVsIdentity']=int(np.max(abs(result[truecaps].astype(int)-identity[truecaps].astype(int))));assert check['polarCapPixelMaxDiffVsIdentity']==0
check['polarBlendProof']='Longitude becomes identity inside4.5-degree polar caps via smooth transition within9-degree latitude-identity caps. There latitude derivative wrt longitude is zero; determinant remains positive.'
# Preserve both coordinates at polar caps by a latitude-dependent longitude blend would break triangular proof.
# Retain the monotone azimuth relabeling at poles; no crossing/holes or newly painted caps.
yy,xx=np.mgrid[:rh,:rw];px=(2*(xx+.5)/rw-1)*t*aspect;py=(1-2*(yy+.5)/rh)*t;norm=np.sqrt(1+px*px+py*py);yaw=np.arctan2(px,1);pitch=np.arcsin(py/norm);vx=((yaw/(2*np.pi)+.5)*w-.5).astype(np.float32);vy=((.5-pitch/np.pi)*hh-.5).astype(np.float32);front=cv2.remap(result,vx,vy,cv2.INTER_LINEAR,borderMode=cv2.BORDER_WRAP);cv2.imwrite(str(out/'forward45-v2.png'),front);ref=cv2.imread(r['reference']['path']);cv2.imwrite(str(out/'forward-overlay-v2.png'),cv2.addWeighted(ref,.5,front,.5,0))
record={'schemaVersion':1,'operation':'Generated-V2-only triangular monotone inverse projection; no original-frame texture, color blending or painting','input':r['panorama'],'registrationSha256':sha(a.registration),'camera':{'yawRadians':0,'pitchRadians':0,'verticalFovDegrees':45,'aspect':aspect,'status':'Authored display lens; not measured video lens'},'output':{'path':name,'sha256':sha(out/name),'width':w,'height':hh},'mapping':{'longitude':'Raw-frame x at mid-row mapped by homography into V2, composed with tan(target longitude), monotone PCHIP to unchanged rear15-degree bands','latitude':'Full homography y for current source column, composed with perspective tan(latitude)/cos(longitude); per-column monotone PCHIP to identity9-degree polar latitude caps; smooth weight to identity rear','omission':'Small homography x/y cross-coupling omitted to keep longitude independent of latitude and guarantee positive determinant','horizon':'Perspective center row maps continuously through homography; no detached rectangular overlay','checks':check,'proof':'Triangular map away from polar transition; within the transition latitude is identity, so the extra longitude/latitude cross term has no determinant contribution. Positive derivative minima checked analytically including segment extrema.'},'scriptSha256':sha(__file__),'limits':'Image-model redraw differences remain. Rear bands and true4.5-degree polar caps are coordinate/pixel identical to identity resampling. The9-degree polar transition changes azimuth continuously, not source art. Surroundings have changed angular spacing. This is not recovery of a physical camera.'};(out/'projection-v2.json').write_text(json.dumps(record,indent=2)+'\n');np.savez_compressed(out/'monotone-coordinate-map-v2.npz',u=mapu[::4,::4],v=mapv[::4,::4]);print(json.dumps(check));print(json.dumps(record['output']))
