#!/usr/bin/env python3
"""Register raw coordinates to generated flat pixels. Output samples generated art only."""
import argparse,hashlib,json,pathlib
import cv2,numpy as np
ap=argparse.ArgumentParser();ap.add_argument('--reference',required=True);ap.add_argument('--panorama',required=True);ap.add_argument('--out',required=True);a=ap.parse_args();out=pathlib.Path(a.out);out.mkdir(parents=True,exist_ok=True)
sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();ref=cv2.imread(a.reference);pano=cv2.imread(a.panorama);h,w=ref.shape[:2]
sift=cv2.SIFT_create(nfeatures=15000,contrastThreshold=.015);k1,d1=sift.detectAndCompute(cv2.cvtColor(ref,cv2.COLOR_BGR2GRAY),None);k2,d2=sift.detectAndCompute(cv2.cvtColor(pano,cv2.COLOR_BGR2GRAY),None);pairs=cv2.BFMatcher().knnMatch(d1,d2,k=2);good=[m for m,n in pairs if m.distance<.72*n.distance];p1=np.array([k1[m.queryIdx].pt for m in good]);p2=np.array([k2[m.trainIdx].pt for m in good]);H,mask=cv2.findHomography(p1,p2,cv2.RANSAC,3.0);use=mask.ravel().astype(bool);pred=cv2.perspectiveTransform(p1[None,:,:],H)[0];err=np.linalg.norm(pred-p2,axis=1)
render=cv2.warpPerspective(pano,np.linalg.inv(H),(w,h),flags=cv2.INTER_LINEAR);cv2.imwrite(str(out/'front-homography.png'),render);cv2.imwrite(str(out/'front-overlay.png'),cv2.addWeighted(ref,.5,render,.5,0));cv2.imwrite(str(out/'flat-matches.jpg'),cv2.drawMatches(ref,k1,pano,k2,[m for m,b in zip(good,use) if b],None,flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS));bounds=[float(p1[use,0].min()/w),float(p1[use,1].min()/h),float(p1[use,0].max()/w),float(p1[use,1].max()/h)]
rec={'schemaVersion':1,'operation':'Raw-frame XY to generated flat-panorama XY homography; diagnostic output samples generated panorama only','reference':{'path':a.reference,'sha256':sha(a.reference),'width':w,'height':h},'panorama':{'path':a.panorama,'sha256':sha(a.panorama),'width':pano.shape[1],'height':pano.shape[0]},'matrixRawXYToFlatPanoramaXY':H.tolist(),'features':{'ratioMatches':len(good),'ransacInliers':int(use.sum()),'medianInlierErrorSourcePanoramaPixels':float(np.median(err[use])),'p90InlierErrorSourcePanoramaPixels':float(np.percentile(err[use],90)),'rawInlierBoundsNormalized':bounds},'correspondences':[{'rawXY':x.tolist(),'flatPanoramaXY':y.tolist(),'inlier':bool(b),'error':float(e)} for x,y,b,e in zip(p1,p2,use,err)],'outputs':[{ 'path':n,'sha256':sha(out/n)} for n in ['front-homography.png','front-overlay.png','flat-matches.jpg']],'scriptSha256':sha(__file__),'note':'No original-frame pixels enter output art. Image-model changes may remain after projective registration. Whole-machine inspection required.'};(out/'homography.json').write_text(json.dumps(rec,indent=2)+'\n');print(json.dumps(rec['features']));print(H)
