import json
from pathlib import Path
base=Path(__file__).parent
if (base/'chapter.json').exists():
 raise SystemExit('Initial planning script only: chapter.json already exists. Use sync_manifest.py for reviewed selections.')
rows=[
('school','A familiar afternoon','Wide from southwest, all four by central stump.','PinPin left-front, Lulu center, Tutu right-front; owl on central stump. Pavilion far-left, oak far-right. No props.', 'В один из дней в Лесной академии учительница Сова собрала Пин-Пина, Лулу и Туту на полянке.', 'One afternoon at the Forest Academy, their owl teacher gathered PinPin, Lulu and Tutu in the clearing.', 'Una tarde, en la Academia del Bosque, la maestra Búho reunió a PinPin, Lulu y Tutu en el claro.'),
('school','A different kind of lesson','Medium four-shot at child height, teacher right and pupils left.','Owl on same stump; three friends look toward teacher.','— Сегодня попробуем услышать то, мимо чего обычно пробегаем, — сказала Сова.', '“Today, let’s listen for the things we usually hurry past,” said their teacher.', '—Hoy vamos a escuchar lo que solemos pasar por alto cuando corremos —dijo la maestra.'),
('school','First, be still','Low intimate three-shot, owl outside frame right.','PinPin left Lulu middle Tutu right, comfortable still paws, no props.','Друзья перестали разговаривать. Пин-Пин замер и прислушался.', 'The friends stopped talking. PinPin held still and listened.', 'Los amigos dejaron de hablar. PinPin se quedó quieto y escuchó.'),
('school','Lulu hears leaves','Medium on Lulu looking up, PinPin and Tutu low beside her.','Lulu raises ears toward canopy; feet remain ground; no pointing extra forelimbs.','Лулу подняла уши. — Слышите? Листья шепчутся над нами.', 'Lulu lifted her ears. “Listen. The leaves are whispering above us.”', 'Lulu levantó las orejas. —¿Lo oyen? Las hojas susurran sobre nosotros.'),
('school','The wind passes through','Upward canopy shot, no cast.','Oak leaves sunlit, no literal faces or music symbols.','Ветер перебирал листья. Ш-ш-ш… Потом стих, и листья снова замерли.', 'The breeze stirred the leaves. Shhh… Then it eased, and the leaves grew still again.', 'La brisa movió las hojas. Shhh… Después se calmó, y las hojas quedaron quietas otra vez.'),
('school','Another sound','Close PinPin turning left toward stream, ears attentive.','PinPin only. Stream direction camera-left, grass foreground.','Теперь Пин-Пин услышал другое: тихое журчание где-то за травой. — А это что?', 'Now PinPin heard something else: a soft trickle beyond the grass. “What’s that?”', 'Entonces PinPin oyó algo más: un murmullo suave al otro lado de la hierba. —¿Qué es eso?'),
('school','Following the trickle','Wide lateral group walking toward left stream bank.','Owl on ground leads left, Lulu then PinPin then Tutu follow on dry path.','Сова повела друзей по тропинке к ручью. Они шли медленно, чтобы не потерять тихий звук.', 'Their teacher led them along the path toward the stream. They walked slowly, keeping the quiet sound in their ears.', 'La maestra los guio por el sendero hacia el arroyo. Caminaron despacio, atentos a aquel sonido suave.'),
('school','A place on the bank','Medium group on dry bank, stream leftforeground.','Owl right/rear supervises; children evenly spaced safely behind edge, boulder left.','На сухом берегу нашлось место для всех. Вода была совсем рядом, но заходить в неё не понадобилось.', 'There was room for everyone on the dry bank. The water was close enough to hear without stepping into it.', 'En la orilla seca había sitio para todos. Podían escuchar el agua de cerca sin entrar en ella.'),
('school','Water and stones','Close stream at pebble level, no animals.','Clear shallow water flows among small rounded stones, no treasure or new object.','Вода огибала камешки и собиралась в маленькие струйки. Каждая журчала чуть по-своему.', 'Water slipped around the pebbles and gathered into little streams. Each made a slightly different sound.', 'El agua rodeaba las piedritas y formaba pequeños hilos. Cada uno sonaba un poco distinto.'),
('school','Tutu hears a tapping','Medium on Tutu beside bank, others partly visible.','Tutu turns toward rear/north pale snag; single tail, two forepaws.','Туту вдруг повернула голову. — Тук-тук-тук! Кто-то стучит. Слышите?', 'Suddenly Tutu turned her head. “Tap-tap-tap! Someone’s knocking. Can you hear it?”', 'De pronto, Tutu giró la cabeza. —¡Toc, toc, toc! Alguien está golpeando. ¿Lo oyen?'),
('school','The next bend','Rear threequarter wide, group follows path away from stream toward pale snag.','Teacher leads, all4 on earthpath; streamleft behind; pale trunk ahead, no crossing.','Они отошли от ручья и пошли на стук. За поворотом тропинки показался светлый сухой ствол.', 'They left the stream and followed the tapping. Around the bend stood a pale, weathered tree trunk.', 'Se alejaron del arroyo y siguieron los golpecitos. Tras una curva apareció un tronco seco y claro.'),
('school','The busy woodpecker','Medium telephoto woodpecker on pale trunk; no school cast.','One small natural black-white-red woodpecker attached to trunk, coherent wings/feet.','На стволе работал дятел. Он остановился на миг — и снова застучал клювом.', 'A woodpecker was busy on the trunk. It paused for a moment, then tapped again.', 'Un pájaro carpintero trabajaba en el tronco. Se detuvo un instante y volvió a golpear con el pico.'),
('school','Watching quietly','Low medium friends+teacher look up, trunk edge left.','All4 on dry earth at respectful distance, no touchingbird; owl folded wings.','Друзья смотрели снизу и не мешали ему. Даже Туту говорила шёпотом.', 'The friends watched from below and left the bird to its work. Even Tutu spoke in a whisper.', 'Los amigos miraron desde abajo y dejaron que el pájaro siguiera trabajando. Hasta Tutu hablaba en voz baja.'),
('school','Back through the garden','Wide returning group, central stump ahead; preserve site.','Return path rightward from snag toward central lawn, owl groundsame, bird not needed.','— Лес звучал всё время, — сказал Пин-Пин по дороге обратно. — Просто я раньше так внимательно не слушал.', '“The forest was making sounds all along,” PinPin said on the way back. “I just wasn’t listening so carefully.”', '—El bosque sonaba todo el tiempo —dijo PinPin al volver—. Yo no lo había escuchado con tanta atención.'),
('school','Remembering together','Medium four-shot by stump, children exchange glances.','Owl perched again; PinPin left Lulu center Tutu right.','Лулу вспомнила листья, Туту — дятла, а Пин-Пин — ручей. Из одной прогулки каждый принёс своё воспоминание.', 'Lulu remembered the leaves, Tutu the woodpecker, and PinPin the stream. Each had something different to remember from the same walk.', 'Lulu recordó las hojas; Tutu, al pájaro carpintero; y PinPin, al arroyo. Cada uno se llevó un recuerdo distinto del mismo paseo.'),
('school','The lesson ends','Wide teacher goodbye and children turning towardoakright.','Owl remains stump; children begin depart right; no waved human fingers.','На этом урок закончился. Друзья поблагодарили Сову, но расходиться им ещё не хотелось.', 'The lesson was over. The friends thanked their teacher, but they weren’t ready to go their separate ways.', 'La clase había terminado. Los amigos le dieron las gracias a la maestra, pero todavía no querían separarse.'),
('oak','A place for three','Wide friends walking from lawnleft to oakright.','Exactly3 friends; teacher absent; crown not started.','— Посидим под дубом? — предложила Лулу. Между большими корнями было три уютных местечка.', '“Shall we sit under the oak?” suggested Lulu. Between its big roots were three comfortable little places.', '—¿Nos sentamos bajo el roble? —propuso Lulu. Entre las grandes raíces había tres rinconcitos cómodos.'),
('oak','Settling in','Mediumwide three friends settled root hollows, southwestview.','Permanent oak seating leftLulu centerPinPin rightTutu. All seatedfeet grounded.','Лулу устроилась слева, Пин-Пин — посередине, а Туту свернула хвост возле правого корня.', 'Lulu settled on the left, PinPin in the middle, and Tutu curled her tail beside the root on the right.', 'Lulu se acomodó a la izquierda; PinPin, en el centro; y Tutu enroscó la cola junto a la raíz de la derecha.'),
('tale','Tutu remembers a story','Medium three-shot emphasis Tutu right speakingtoleft.','Tutu one tail, hands empty, listeners faceher; no actualjar.','— А знаете, что на прошлой неделе случилось с енотом? — начала Туту. — Он никак не мог открыть банку мёда!', '“Do you know what happened to a raccoon last week?” Tutu began. “He couldn’t get a honey jar open!”', '—¿Saben lo que le pasó a un mapache la semana pasada? —empezó Tutu—. ¡No podía abrir un tarro de miel!'),
('tale','Pulling an imaginary lid','Close Tutu mime pulling lid with twoforepaws, nojar.','Seatedright hollow, bodyfacesleft, other2 offscreenleft.','Туту показала, как енот тянул крышку. — Он пыхтел, сопел и даже сказал банке: «Ну пожалуйста!»', 'Tutu showed them how he pulled at the lid. “He huffed and puffed. He even said to the jar, ‘Oh, please!’”', 'Tutu les mostró cómo tiraba de la tapa. —Resopló y bufó. ¡Hasta le dijo al tarro: «Por favooor»!'),
('tale','The jar did not answer','Medium all3 laughing natural, Tutu animated butgrounded.','SameleftLulu centerPinPin rightTutu; nojar/raccoon.','— А потом он повернул крышку — и она открылась! «Что же ты сразу не сказала?» — спросил он банку. Друзья расхохотались.', '“Then he turned the lid—and it opened! ‘Why didn’t you say so?’ he asked the jar.” The friends burst out laughing.', '—¡Entonces giró la tapa y se abrió! «¿Por qué no lo dijiste antes?», le preguntó al tarro. Los amigos soltaron una carcajada.'),
('crown','Daisies by the root','Medium Lulu noticesflowersleftforeground othersrelaxbehind.','Lulu stillseatedleft thenleans towardpatch; no crown.','Когда смех стих, Лулу заметила рядом с корнем маргаритки. — Сделаю маленький венок, — сказала она.', 'As their laughter faded, Lulu noticed the daisies beside the root. “I’ll make a little crown,” she said.', 'Cuando se apagaron las risas, Lulu vio las margaritas junto a la raíz. —Voy a hacer una coronita —dijo.'),
('crown','A small handful','Medium Lulu ongroundbesidepatch, holdsfewstems; friendsbehind.','Lulu left ofroot seat nowatpatch; a few daisies gathered, many remain.','Она спустилась к цветам и собрала несколько длинных стебельков. Большинство маргариток осталось расти у дуба.', 'She stepped down to the flowers and gathered a few long stems. Most of the daisies stayed growing beside the oak.', 'Bajó hasta las flores y recogió unos pocos tallos largos. La mayoría de las margaritas siguió creciendo junto al roble.'),
('crown','One stem after another','Close Lulu seatedagainleft, forepawsweavingshortopenchain.','Short unfinished chain and looseflowers onrootbesideher; no completecrownyet.','Вернувшись на своё место, Лулу осторожно переплела стебельки: один за другим, цветок за цветком.', 'Back in her place, Lulu carefully wove the stems together: one after another, flower after flower.', 'De vuelta en su sitio, Lulu entrelazó los tallos con cuidado: uno tras otro, flor tras flor.'),
('crown','Watching the work','Mediumtwo-shot Luluweavingleft PinPinwatchright.','PinPin seatedcenterhandsrelaxed; Luluholds longeropenflowerchain; Tutuoffscreenright.','Пин-Пин придвинулся, чтобы посмотреть. Он подождал, пока Лулу закончит очередной стебелёк, и только потом заговорил.', 'PinPin leaned closer to watch. He waited for Lulu to finish the next stem before speaking.', 'PinPin se acercó para mirar. Esperó a que Lulu terminara con el siguiente tallo antes de hablar.'),
('crown','Joining the ends','Mediumclose Lulu holding finishedsmalldaisyringbeforechest.','Ringcomplete heldintwopaws, stillnotonhead, earsclear.','— И как же он станет круглым? — спросил он. Лулу соединила два конца. — Вот так.', '“How does it become a circle?” he asked. Lulu joined the two ends. “Like this.”', '—¿Y cómo se hace redonda? —preguntó. Lulu unió los dos extremos. —Así.'),
('crown','A crown for Lulu','Mediumall3 Lulu crownwornatbaseears, friendswarmapproval.','White daisy crown onLulu head between/aroundbaseears, notonPinPin/Tutu.','Лулу примерила венок. Туту улыбнулась. — Как будто у тебя на голове кусочек нашей полянки!', 'Lulu tried on the crown. Tutu smiled. “It’s like wearing a little piece of our clearing!”', 'Lulu se probó la corona. Tutu sonrió. —¡Parece que llevas un pedacito de nuestro claro en la cabeza!'),
('quiet','Listening again','MediumLulu eyesgentlyclosed wearingcrown, friendsstill.','Sameoakpositions, sunsetwarmer. No magic symbols.','Лулу закрыла глаза. — Иногда я просто слушаю лес. И чувствую, что мне здесь хорошо.', 'Lulu closed her eyes. “Sometimes I just listen to the forest. And I feel that I belong here.”', 'Lulu cerró los ojos. —A veces solo escucho el bosque. Y siento que este es mi lugar.'),
('quiet','Part of the sound','ClosePinPin lookingsoftlyup smile, oakmossbehind.','OnlyPinPin, seatcenter, noaddedcrown.','Пин-Пин прислушался к листьям и далёкому ручью. — Мы тоже здесь, — сказал он. — Наш смех ведь тоже слышно.', 'PinPin listened to the leaves and the distant stream. “We’re here too,” he said. “Our laughter is one of the sounds.”', 'PinPin escuchó las hojas y el arroyo lejano. —Nosotros también estamos aquí —dijo—. Nuestras risas también forman parte de los sonidos.'),
('quiet','The quiet between friends','Wide oak threefriends resting sunset, pavilionleftdistant.','Lulucrownleft PinPincenter Tuturight; friendsquiet, no teacher.','Потом они помолчали вместе. Небо розовело, листья шелестели, и никто не торопился нарушить эту тишину.', 'Then they sat quietly together. The sky turned pink, the leaves rustled, and none of them hurried to break the silence.', 'Después se quedaron juntos en silencio. El cielo se tiñó de rosa, las hojas susurraron y ninguno tuvo prisa por romper aquella calma.'),
('home','Mama on the path','Widepathforegroundright Mamaapproaching oakbackgroundleft.','Mamaonlyforeground, threefriends smallinoakdistance; Lulu crown.','По тропинке показалась Мама. Она увидела друзей под дубом и на минутку замедлила шаг.', 'Mama appeared on the path. When she saw the friends beneath the oak, she slowed her steps for a moment.', 'Mamá apareció en el sendero. Al ver a los amigos bajo el roble, aflojó el paso un momento.'),
('home','A familiar voice','MediumPinPin atrootturningright towardoffscreenMama.','PinPincenterroot riseshead; Lululeftcrown Tuturightstayseated.','— Пин-Пин, пора домой, — мягко позвала она. Среди всех лесных звуков он сразу узнал её голос.', '“PinPin, it’s time to go home,” she called softly. Among all the forest sounds, he knew her voice at once.', '—PinPin, es hora de volver a casa —llamó con dulzura. Entre todos los sonidos del bosque, él reconoció su voz enseguida.'),
('home','Down from the roots','MediumMama right PinPin walkingfromoaklefttowardher.','PinPin onground nojump/airborne; friendsseatedbehind, Lulu crown.','Пин-Пин спустился с корня и подошёл к Маме. Но прежде чем уйти, он обернулся к друзьям.', 'PinPin stepped down from the root and went to Mama. Before leaving, he turned back toward his friends.', 'PinPin bajó de la raíz y se acercó a Mamá. Antes de irse, se volvió hacia sus amigos.'),
('home','Until next time','WideMamaPinPin foregroundright facingfriends atoakleft.','Lulucrown andTutu remainroot, PinPinoneforepawgoodbye; Mamanearhim.','— До встречи! — сказал он. Лулу и Туту помахали ему. Венок остался у Лулу, а смех этого дня — у всех троих.', '“See you soon!” he said. Lulu and Tutu waved. Lulu kept her flower crown, and all three kept the day’s laughter.', '—¡Hasta pronto! —dijo. Lulu y Tutu lo saludaron. Lulu se quedó con la corona, y los tres se llevaron las risas de aquel día.'),
('home','The walk home','LateralmediumwideMamaandPinPin walkrightforestpathdusk.','Only2hedgehogs, Mama2xPinPin, no crown, no academy backgroundneed.','По дороге Пин-Пин рассказал Маме о ручье, дятле и смешной банке мёда. Потом они немного послушали лес вместе.', 'On the way home, PinPin told Mama about the stream, the woodpecker and the funny honey jar. Then they listened to the forest together for a while.', 'De camino a casa, PinPin le contó a Mamá lo del arroyo, el pájaro carpintero y el gracioso tarro de miel. Después escucharon juntos el bosque un ratito.'),
('home','Their familiar doorway','Rear3quarterMamaandPinPin approachgreenrounddoorhome.','Establishedcottageexterior dusk, Mama left PinPinright, doorcloseduntilarrival, no extra family.','Наконец впереди засветились знакомые окна. — Мы дома, — сказала Мама. И Пин-Пин довольно вздохнул.', 'At last, their familiar windows glowed ahead. “We’re home,” said Mama. PinPin gave a happy little sigh.', 'Por fin brillaron delante de ellos las ventanas conocidas. —Ya estamos en casa —dijo Mamá. PinPin suspiró contento.'),
]
seq=[('school','Слушаем лес','Listening to the forest','Escuchamos el bosque'),('oak','Под старым дубом','Beneath the old oak','Bajo el viejo roble'),('tale','История Туту','Tutu’s story','La historia de Tutu'),('crown','Венок Лулу','Lulu’s flower crown','La corona de Lulu'),('quiet','Хорошо быть вместе','Happy to be together','Qué bien estar juntos'),('home','Мама зовёт домой','Mama calls us home','Mamá nos llama a casa')]
manifest={'schemaVersion':1,'id':'academy','sourceChapter':'chapter-04','status':'proposed','title':{'ru':'Академия Леса','en':'The Forest Academy','es':'La academia del bosque'},'summary':{'ru':'Одна прогулка учит друзей прислушиваться. После уроков у старого дуба хватает времени для истории, венка и тихой дружбы.','en':'One listening walk helps the friends notice their forest. After class, there is time for a story, a flower crown and quiet friendship beneath the oak.','es':'Un paseo para escuchar ayuda a los amigos a descubrir su bosque. Después de clase hay tiempo para una historia, una corona de flores y la amistad bajo el roble.'},'cover':{},'preproduction':[{'id':'cast','title':'Canonical cast','src':'images/chapter-04-academy/preproduction/cast-v1.png','description':'PinPin, Lulu, Tutu and proposed owl teacher; internally reviewed identity study.'},{'id':'site','title':'Academy site','src':'images/chapter-04-academy/preproduction/site-v1.png','description':'Pavilion left, stream left, stump center, snag rear, oak right; geography reference.'},{'id':'oak','title':'Oak root clean plate','src':'images/chapter-04-academy/preproduction/oak-plate-v1.png','description':'Three dry root hollows, daisies left, southeast departure path.'}],'sequences':[{'id':x[0],'title':dict(zip(['ru','en','es'],x[1:])),'purpose':'Expand physical and emotional continuity through distinct actions and reactions.'} for x in seq],'scenes':[], 'editorialNotes':['Original chapter4 repeats the same seven-beat afternoon passage twice; adapted once.','Ordinary later school day, not the morning after chapter3 or first-ever school day.','Owl teacher, outdoor academy and listening walk are adaptation additions.','Raccoon anecdote has a newly written gentle punch line and stays an orally told story, not a flashback.','Daisy gathering/weaving stages and home threshold expand compressed source actions.'], 'continuityNotes':['Elder’s next-dawn invitation remains a future story thread, not depicted or cancelled here.','Lulu is rabbit, Tutu squirrel; established PinPin and Mama identities.','School garden consistent landmark geography; no invented interior used.','Lulu retains the crown at the oak; PinPin and Mama go home without it.']}
shots=[]
for n,row in enumerate(rows,1):
 sid,heading,camera,continuity,ru,en,es=row
 kind='new' if n<=16 else 'expanded'
 blocks=[] if n<=16 else ([1] if n<=18 else [2] if n<=21 else [3] if n<=28 else [4] if n==29 else [5] if n==30 else [6] if n<=34 else [7])
 scene={'id':f'academy-{n:02}','sequence':sid,'src':f'images/chapter-04-academy/scenes/scene-{n:02}-v1.png','width':1536,'height':1024,'alt':{'ru':ru,'en':en,'es':es},'text':{'ru':[ru],'en':[en],'es':[es]},'source':{'kind':kind,'blocks':blocks,'note':'Proposed classroom activity' if n<=16 else 'Source event expanded into action/reaction/transition; narration adds concrete staging.'},'camera':camera,'continuity':continuity,'review':'Pending generation and visual inspection.','reused':False}
 manifest['scenes'].append(scene)
 shots.append({'id':scene['id'],'title':heading,'order':n,'source':scene['source'],'action':en,'camera':camera,'castAndPositions':continuity,'propState':'No schoolprops. Daisy crown progresses scenes23–27 and remains Lulu through34.','status':'planned'})
(base/'chapter.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
(base/'shot-plan.json').write_text(json.dumps({'schemaVersion':1,'chapter':'academy','plannedBeforeProduction':True,'shots':shots},ensure_ascii=False,indent=2)+'\n')
print(len(rows),'scenes planned')
