import json,copy
from pathlib import Path
D=Path(__file__).parent; B=D.parents[5]; OLD=json.loads((D.parents[2]/'revision-05/elder/chapter.json').read_text()); old={int(s['id'].split('-')[-1]):s for s in OLD['scenes']}
parts=[];counter=0
T=lambda en,ru,es:dict(en=en,ru=ru,es=es)
def start(id,title,summary):
 p=dict(id=id,title=T(*title),summary=T(*summary),scenes=[]);parts.append(p);return p
p=start('papa-home',('Papa Comes Home','Папа возвращается','Papá vuelve a casa'),('A misty arrival becomes a morning of hugs, play and breakfast preparations.','Туманное утро наполняется объятиями, играми и хлопотами к завтраку.','Una llegada entre la niebla se convierte en una mañana de abrazos, juegos y preparativos.'))
def reuse(n,text=None):
 global counter
 counter+=1;s=copy.deepcopy(old[n]);s.update(id=f'elder-r6-family-{counter:03d}',previousID=old[n]['id'],reused=True,assetMode='reuse',sequence=p['id']);s.pop('before',None);s.pop('beforeText',None);s.pop('beforeNote',None)
 if text:s['text']={k:[v] for k,v in T(*text).items()}
 p['scenes'].append(s)
def new(slug,en,ru,es,action,loc='K',previous=None):
 global counter
 counter+=1
 s=dict(id=f'elder-r6-family-{counter:03d}',slug=slug,previousID=f'elder-r5-{previous:03d}' if previous else None,sequence=p['id'],text={k:[v] for k,v in T(en,ru,es).items()},source={'kind':'new','blocks':[],'note':'User-authorized revision06 family expansion; lake retelling follows original chapter01.'},camera=action,continuity='Exact family cast: Papa, Mama, PinPin, infant PomPom. No Elder. Explicit handoffs and fixed meal seats.',review='Pending render and actual review',reused=False,assetMode='edit' if previous else 'new',src=f'images/chapter-02-expanded/revision-06/family/{slug}-v1.png',width=1536,height=1024,alt=T(action,action,action),location=loc)
 p['scenes'].append(s)
for n in [1,4,2,3,5]:reuse(n)
new('handoff','“My turn to hold you,” said Papa. Mama kept one paw beneath PomPom while Papa slipped both arms around him.','— Теперь я тебя подержу, — сказал Папа. Мама поддерживала Пом-Пома снизу, пока Папа обнимал его обеими лапами.','—Ahora te abrazo yo —dijo Papá. Mamá sostuvo a PomPom por debajo mientras Papá lo rodeaba con ambos brazos.','Threshold medium profile: Mama left securely transfers infant to Papa right, all four forearms readable; PinPin foreground watches. Scooby outside left background.','H')
new('papa-cradle','PomPom caught Papa’s paw. “You remember me!” Papa laughed. PinPin leaned close to see.','Пом-Пом ухватился за Папину лапу. — Узнал меня! — засмеялся Папа. Пин-Пин придвинулся поближе.','PomPom agarró la pata de Papá. —¡Me reconoces! —rio Papá. PinPin se acercó para mirar.','Close family triangle Papa cradles baby in two forearms, baby grips one finger; PinPin at side reaches only to Papa knee. Mama visible background doorway.','H')
new('floor-settle','Inside, Papa sat on the rug with PomPom on his lap. PinPin sat beside them.','В доме Папа сел на ковёр и устроил Пом-Пома у себя на коленях. Пин-Пин сел рядом.','Dentro, Papá se sentó en la alfombra con PomPom en su regazo. PinPin se sentó a su lado.','Kitchen wide floor-level: Papa seated on rug left of table infant supported lap; PinPin kneels beside Papa; Mama at left counter arranging bread. Table not laid yet.')
new('peekaboo','PinPin covered his face. “Where is PinPin?” Papa asked. PomPom leaned forward.','Пин-Пин закрыл мордочку лапами. — Где же Пин-Пин? — спросил Папа. Пом-Пом потянулся вперёд.','PinPin se tapó la cara. —¿Dónde está PinPin? —preguntó Papá. PomPom se inclinó hacia delante.','Low intimate over Papa shoulder toward PinPin covering face with both paws; infant on Papa lap clearly supported, Mama counter background.')
new('found-you','“Here!” PinPin opened his paws. PomPom squealed, and Papa laughed with them.','— Вот он я! — Пин-Пин развёл лапы. Пом-Пом радостно пискнул, и Папа засмеялся вместе с ними.','—¡Aquí! —PinPin abrió las patas. PomPom soltó un gritito y Papá rio con ellos.','Same floor play axis slightly wider: PinPin face revealed paws open, baby reaches toward him from Papa secure lap, Papa joyful readable eyes, Mama smiles from counter.')
new('bread-helper','“Will someone carry the bread?” Mama asked. PinPin sprang up. “I will!”','— Кто отнесёт хлеб? — спросила Мама. Пин-Пин вскочил: — Я!','—¿Quién lleva el pan? —preguntó Mamá. PinPin se levantó de un salto. —¡Yo!','Counter three-quarter at childheight: Mama lowers wooden bread platter into PinPin two supporting paws; Papa and baby clearly visible rug behind.')
new('bread-table','PinPin carried the plate with both paws. Papa watched him set it carefully on the table.','Пин-Пин нёс тарелку обеими лапами. Папа смотрел, как он осторожно ставит её на стол.','PinPin llevó el plato con ambas patas. Papá lo miró colocarlo con cuidado en la mesa.','Table rim level: PinPin stands stable stool placing bread platter at tablefront-left; Papa sitting floor baby lap beyond, Mama at counter. No breakfast bowls yet.')
new('baby-back','Mama sat down. Papa settled PomPom into her arms, and the little one snuggled close.','Мама села. Папа передал Пом-Пома ей на руки, и малыш уютно прижался к ней.','Mamá se sentó. Papá acomodó a PomPom entre sus brazos y el pequeño se acurrucó.','Kitchen left-seat handoff medium: Mama seated left of roundtable receiving baby, Papa standing beside her fully supporting baby during transfer; PinPin at right chair with breadtable visible.')
new('cups-ready','Papa brought the cups. PinPin put one beside each bowl. “Now everyone has a place.”','Папа принёс кружки. Пин-Пин поставил по кружке возле каждой миски. — Теперь всем хватило места.','Papá trajo las tazas. PinPin puso una junto a cada cuenco. —Ya tenemos sitio todos.','Higher kitchen table action wide: Papa far-right lowers final pottery cup; PinPin near-right arranges his cup; Mama left holds PomPom. Exact3 bowls3cups breadfront-left communalporridgecenter teapotnearPapa. All four visible.')
reuse(6)
p=start('family-morning',('A Morning Together','Утро всей семьёй','Una mañana en familia'),('Breakfast stories, shared little jobs, and preparations for a visit.','Рассказы за завтраком, общие дела и сборы в гости.','Historias durante el desayuno, pequeñas tareas compartidas y preparativos para una visita.'))
new('lake-news','“Lulu told me the lake was dry,” PinPin began. Papa set down his cup. Mama turned to listen too.','— Лулу сказала, что озеро высохло, — начал Пин-Пин. Папа поставил кружку. Мама тоже повернулась к нему.','—Lulu me dijo que el lago estaba seco —empezó PinPin. Papá dejó la taza. Mamá también se volvió para escucharlo.','Breakfast medium-wide from tablefront-left: PinPin right tells story, Papa far-right sets cup down looking at child, Mama left baby lap listening. All four visible fixed same3bowls3cups and platter.',previous=7)
new('circle-telling','“I drew a circle with my golden quill. The water came up right in the middle!” His paw drew a circle in the air.','— Я нарисовал круг золотой иголочкой. А вода появилась прямо в середине! — Его лапа описала круг в воздухе.','—Dibujé un círculo con mi púa dorada. ¡El agua salió justo en el centro! —Su pata trazó un círculo en el aire.','Breakfast child-side low angle but all four in frame: PinPin foreground near-right draws circle in air above bowl, empty paw, Papa beyond watching, Mama/baby left. No new magic effect.')
new('everyone-water','“Was there enough for everyone?” Papa asked. “Yes! They drank and splashed and swam!”','— Всем хватило воды? — спросил Папа. — Да! Все пили, плескались и плавали!','—¿Hubo agua para todos? —preguntó Papá. —¡Sí! ¡Bebieron, chapotearon y nadaron!','Breakfast across Mama shoulder with her and infant visible foreground-left, Papa center leaning engaged to child right, child opens two paws enthusiastically. Fixed vessels no extra cast.',previous=8)
new('mama-bread','Mama passed PinPin a piece of bread. “Then everyone had a very good day.”','Мама протянула Пин-Пину кусочек хлеба. — Значит, у всех был очень хороший день.','Mamá le pasó un trozo de pan a PinPin. —Entonces todos tuvieron un día muy bonito.','Breakfast frontal context all4: Mama left baby securely held oneforearm/lap otherpaw passes bread toward PinPinright, Papa far-right smiles holdingcup. Maintain3bowls3cups.',previous=10)
new('little-spill','PinPin reached for the bread—and nudged his cup. A little water ran across the table. “Oh!”','Пин-Пин потянулся за хлебом и задел кружку. По столу побежала вода. — Ой!','PinPin fue a tomar el pan y rozó su taza. Un poco de agua corrió por la mesa. —¡Uy!','Table near-right detail with four recognizable family faces in upperframe: PinPin cup tipped towardemptytablefront little clearwater spill, Papa movingcloth towardspill, Mama supportsbaby left. No hot tea spill onchild.')
new('wipe-together','“Hold this end,” said Papa. Together they caught the little river with a cloth.','— Держи этот край, — сказал Папа. Вместе они поймали маленькую речку полотенцем.','—Sujeta este lado —dijo Papá. Juntos atraparon el pequeño río con un paño.','Same table angle closer hands action all4faces present: Papa andchild eachholdoppositeend beigecloth wiping smallspill, cup upright again, Mama/babywatchleft.')
new('clear-table','After breakfast, PinPin carried his empty bowl to Mama. Papa brought the other dishes.','После завтрака Пин-Пин отнёс Маме пустую миску. Папа принёс остальную посуду.','Después del desayuno, PinPin llevó su cuenco vacío a Mamá. Papá llevó los demás platos.','Kitchen wide changeplace: Mama at leftsink baby held against hip withonearm; PinPin bringsonebowl2paws, Papa behind carriesstack2bowls bothpaws. Table strippedonlybreadplate andteapot, noextravessels.')
new('tower-build','On the rug, Papa held a wooden block steady. PinPin put another on top. “One more?”','На ковре Папа придерживал деревянный кубик. Пин-Пин поставил сверху ещё один. — Ещё?','En la alfombra, Papá sujetó un bloque de madera. PinPin puso otro encima. —¿Uno más?','Low floor view newplayzone lefttable: Papa seated holdsbaseblock, PinPin stacks second, Mama seated behind supportingbaby onlap watching. Three unpainted roundedwoodblocks total.')
new('tower-topple','PomPom reached out. Bump! The little tower tumbled onto the rug. Everyone laughed.','Пом-Пом потянулся лапкой. Бух! Башенка рассыпалась по ковру. Все засмеялись.','PomPom estiró una patita. ¡Pum! La torrecita cayó sobre la alfombra. Todos rieron.','Same floor group opposite modestraisedview: baby fromMama supportedlap pats topblock, threeblocks fallinglowontorug, Papa andPinPinlaugh withbaby notscold.')
new('build-again','“Again?” said PinPin. This time he gave PomPom a block of his own.','— Ещё раз? — спросил Пин-Пин. На этот раз он дал Пом-Пому отдельный кубик.','—¿Otra vez? —preguntó PinPin. Esta vez le dio a PomPom su propio bloque.','Floorclose triangle: PinPin passesonewoodblock into baby2paws onMama lap; Papabehind setsother2blocks tower, allfour visible.')
new('ready-visit','Papa looked at Mama. “I think it’s time PinPin met the Elder properly.” Mama smiled. “Yes. He’s ready.”','Папа посмотрел на Маму. — Думаю, пора Пин-Пину поближе познакомиться со Старейшиной. Мама улыбнулась. — Да. Он готов.','Papá miró a Mamá. —Creo que es hora de que PinPin conozca bien al Anciano. Mamá sonrió. —Sí. Está preparado.','Floorgroup wide parents mutualeyes acrosschild: Papa leftMama rightbaby lap, childbetweenlooksPapa, blocks atfeet. Warmordinaryfamilydecisionno solemn initiation.',previous=9)
new('bag-ready','“Today?” asked PinPin. “Today,” said Papa. “We’ll take our lunch.” He fetched the picnic bag.','— Сегодня? — спросил Пин-Пин. — Сегодня, — ответил Папа. — Возьмём с собой обед. Он принёс сумку.','—¿Hoy? —preguntó PinPin. —Hoy —dijo Papá—. Llevaremos el almuerzo. Fue a buscar la bolsa.','Kitchen mediumwide Papa setssmall ochre cloth satchel, one broad diagonal strap leftshoulder to righthip, rounded flap simple wooden toggle oncleartable, PinPin peersinside, Mamababywatchleft.')
new('wrap-bread','PinPin wrapped the bread. Papa tucked it into the bag beside two apples.','Пин-Пин завернул хлеб. Папа уложил его в сумку рядом с двумя яблоками.','PinPin envolvió el pan. Papá lo acomodó en la bolsa junto a dos manzanas.','Topoblique tabletop action Papa andPinPin paws foldingcreamlinen aroundbread into open ochre cloth satchel creamliner2apples, Mamaandbaby faces upperleft present.')
new('water-packed','Mama added a little bottle of water. “For the walk.” PinPin checked the lid with Papa.','Мама добавила небольшую бутылку воды. — На прогулку. Пин-Пин вместе с Папой проверил крышку.','Mamá añadió una botellita de agua. —Para el paseo. PinPin comprobó la tapa con Papá.','Tablemedium Mama left supportsbabyonearm otherpaw insertsstopperedplainbottle bag, Papa andchildrightlookcontents; breadlinen2applescreamliner.')
new('goodbye-hug','Before they went outside, PinPin hugged Mama and gently touched PomPom’s paw. “I’ll tell you everything!”','Перед выходом Пин-Пин обнял Маму и осторожно коснулся лапки Пом-Пома. — Я вам всё расскажу!','Antes de salir, PinPin abrazó a Mamá y tocó con cuidado la patita de PomPom. —¡Les contaré todo!','Inside doorwaylow childhugMama knees sheholdsPomPomtwoarms, Papa behindcarriesclosedbag atside, middaynotnightgreeninnerhingesrightknobleft.')
reuse(11)
new('boarding-help',*([old[12]['text'][l][0] for l in ['en','ru','es']]),'Garden mountingstone: Papa downon ground steadyingchild, ochre satchel crossbody leftshoulder to righthip, dog crouched beside stone; Mama baby doorway. Preserve exact original contacts.',loc='H',previous=12)
new('boarding-seat',*([old[13]['text'][l][0] for l in ['en','ru','es']]),'Garden mountingstone: child seated straddling behinddogwithers Papa supportschild beside stone, ochre crossbodysatchel at righthip awayfromchild, Mama baby doorway.',loc='H',previous=13)
reuse(14)
new('departure',*([old[15]['text'][l][0] for l in ['en','ru','es']]),'Gardendeparture rear3quarter: Papa behindchild onScooby back oneforearmsupportchildotherbracesback, ochre satchel closed securedcrossbody right hip awayfromchild; Mama baby doorway wavesonlyonefreehandwithbabysecure.',loc='H',previous=15)
# Coda is separate supplied to root/mentor.
p=dict(id='afternoon-coda',scenes=[])
new('bag-home','Papa set the empty bag down. PinPin helped Mama fold the picnic cloth.','Папа поставил пустую сумку. Пин-Пин помог Маме сложить полотенце для обеда.','Papá dejó la bolsa vacía. PinPin ayudó a Mamá a doblar el paño del picnic.','Afternoon kitchenwide Papa placesemptyopenbag ontable while Mama andPinPin eachholdcreamclothcornerfolding; baby secureMama lap seatedleft. No mealserved.')
new('tell-mama','“First, a page moved all by itself…” PinPin began. Mama settled PomPom into Papa’s arms while she listened.','— Сначала страница сама собой зашевелилась… — начал Пин-Пин. Мама передала Пом-Пома Папе на руки и стала слушать.','—Primero, una página se movió sola… —empezó PinPin. Mamá acomodó a PomPom en los brazos de Papá mientras escuchaba.','Afternoon rugfamilytriangle Papa seatedright receivingbaby withtwoforearms Mama seatedleft keepsonepaw supportingbaby duringhandoff listenschildcenter gesturingflutterpagehands; emptybag tablebackground. Explicit newbabyhandoff needed preceding or combineMama stillholds.')
new('home-together','PinPin settled beside them. There was still so much to tell—and everyone was there to listen.','Пин-Пин устроился рядом. Ему ещё столько хотелось рассказать — и все были рядом, чтобы послушать.','PinPin se acomodó junto a ellos. Aún tenía mucho que contar, y todos estaban allí para escucharlo.','Afternoon wide intimatefamilyall4floor Mama cuddleschild oneforearm otherholdswoodblock, Papa supportsinfant botharms, childanimatedtalk; warmdaywindows no meal no bed.')
coda=p['scenes']
# initial durable transform plans; per-shot actor states expanded before calls.
for i,s in enumerate([s for p in parts for s in p['scenes']]+coda):
 if s['reused']:continue
 loc=s['location'];isH=loc=='H'; xyz={'Papa':[.7,.8,0],'Mama':[-1.2,0,0],'PinPin':[.9,-.8,0],'PomPom':[-1.2,0,.9],'Scooby':[-2,-2,0]} if not isH else {'Papa':[.6,-1,0],'Mama':[-.6,-.5,0],'PinPin':[0,-2,0],'PomPom':[-.5,-.5,.9],'Scooby':[-3,-2,0]}
 cam=[-3,-4,1.5] if not isH else [2,-5,1.2]
 s['cameraTransform']={'schemaVersion':1,'purpose':s['camera'],'frameId':loc,'units':'Approximate PinPin standing heights; illustrative art direction, not measured geometry.','camera':{'positionXYZ':cam,'targetXYZ':[0,0,.8],'height':cam[2],'framing':s['camera'],'fieldOfViewDegrees':50,'axisSide':'Kitchen negativeY master half-space' if not isH else 'Exterior negativeY'},'actors':[{'name':n,'positionXYZ':v,'bodyFacingTarget':'family interaction','headFacingTarget':'named interaction target in shot action','eyeTarget':'subject of current action','pose':s['camera'],'limbsContactSupport':'Adult two forearms only, both hindfeet or seated haunches supported; infant explicitly supported by named adult. Detailed shot prompt refines these records before call.','visibility':'offscreen outside' if n=='Scooby' and not isH else 'visible'} for n,v in xyz.items()],'staticLandmarks':{'table':[0,0,.85],'greenDoor':[0,3,0],'leftCounter':[-3,1,0],'stove':[3,1,0],'playRug':[-2,-1,0]},'objectStates':{'before':'See scene action and sequential state ledger','after':s['camera']},'transition':{'previousAction':'Previous ordered scene','nextAction':'Next ordered scene','reasonForShotChange':s['camera']}}
json.dump({'parts':parts,'coda':coda,'status':'story plan awaiting root coherence review; transforms will be fully specialized pre-call'},open(D/'story-plan.json','w'),ensure_ascii=False,indent=2)
print([(p['id'],len(p['scenes'])) for p in parts],len(coda))
