import json, pathlib, datetime
p=pathlib.Path(__file__).parent
old=json.loads((p/'../../elder/chapter.json').resolve().read_text())['scenes']
# id, title, camera, visible action/gaze, English draft, optional earlier selected image index
rows=[
('Path to the Elder','E0 wide','PinPin walks away from camera toward hill; eyes on path.', 'The day after he helped the lake, PinPin went to see the oldest hedgehog on Burrow Hill.',1),
('Leaf arch','Low approach','PinPin stops beneath leaf arch, looking up at leaves; no listener.', 'What would a very old, very wise hedgehog be like?',2),
('The root home','E0 wide','PinPin foreground faces Elder distant left of root arch; Elder faces away.', 'There he was, beside a house tucked under the roots of a great tree.',3),
('A greeting without turning','E0 medium','Elder left deliberately faces left away from arriving child right. This is the source surprise, not attempted eye contact.', '“Hello, PinPin,” said the Elder, without turning. “I felt you would come today.”',5),
('How did you know?','Reverse over Elder shoulder','PinPin left looks up/right at visible Elder shoulder right; speaker child, listener Elder.', '“You knew? How?”',6),
('Leaves carry news','Upward canopy insert','No actors; leaf movement is the named listening target.', '“The wind and the leaves bring news,” said the Elder. “I listen.”',7),
('The real question','E0 reciprocal two-shot','Elder left faces child right. Both pupils/heads target partner. Child asks; Elder listens.', '“My golden quill helped the lake,” said PinPin. “Where did its magic come from?” “That is a good question. Come with me.”',9),
('A small thing needs help','E0 plant approach','Both look down/right at trapped plant. Shared attention, no eye-contact claim.', 'On the way to the door, PinPin stopped. “That little plant is stuck.”',12),
('Lift carefully','Plant close','PinPin eyes on branch; two forepaws lift it clear of leaves. No dialogue gaze.', 'He lifted the stick, carefully, so the leaves could unfold.',17),
('A place to grow','E0 plant pair','PinPin sets branch on bare soil right of upright plant; Elder watches action from left.', '“There. Room to grow,” said PinPin. The Elder smiled.',18),
('Through the roots','H entrance continuity','Elder ahead at root threshold looks into room; child behind looking through same opening. Staff remains outside.', '“Now come and see where I keep my questions,” said the Elder.',None),
('A lived-in home','H0 master','Pair at south entrance looking around room. Show desk west, books west, map north, cave door northeast CLOSED, sleep alcove east.', 'Inside were books, rolled maps, a soft bed and a little table stained with ink.',None),
('The Elder writes','H1 table action','Elder left uses one forepaw with dark writing feather; other grounded at page edge; PinPin right watches ink tip.', '“Do you write books?” “Sometimes. Today I was writing down what I noticed.”',None),
('Reading together','H1 reciprocal then book gaze','Elder left has turned face toward child right while holding open book low. Child looks back; page visible below both.', '“Do you know everything?” asked PinPin. “Oh, no,” said the Elder. “That is why I read.”',None),
('Things worth keeping','Artifact close with pair','PinPin right looks at shell/fossil/seed case on low shelf left; Elder behind-left looks at same object. No new wand or future gift.', 'A smooth stone. An empty shell. A seed in a little box. “Small things can make us ask big questions,” said the Elder.',None),
('Where everyone lives','H0 map station','Elder left paw points at lake on simple unlabeled map; PinPin right eyes target lake. Root-home/hill/lake routes legible.', 'PinPin found the lake on a map. All around it were little homes. “So many neighbours!”',None),
('The inner door','H2 closed door','Elder at northeast closed door left of child; turns to child for invitation. Child eyes Elder, not ring.', '“There are older pictures downstairs,” said the Elder. “Would you like to see?” “Yes!”',None),
('Door opens onto a landing','H2 open door','Elder pulls ring door into the room against east wall, child safely behind. Show level top landing before steps; both look at stair route.', 'The wooden door opened. Warm lamps shone down a stone stair.',None),
('First steps down','T0 down first flight','Elder leads below; PinPin one body length behind. Both eyes on shallow broad treads, four limbs plausible. Door remains open above.', '“Slowly,” said the Elder. “One step, then the next.” PinPin followed.',None),
('A safe turn','T1 middle landing','Both stopped on level landing. Elder near turn faces back to PinPin; reciprocal gaze. First flight rises behind, next descends south.', 'At the turn, the Elder waited. “All right?” “All right,” said PinPin.',None),
('Light below','T2 second flight','Pair descend toward camera/bottom cave entry; Elder first. Bright shaft-lit cave slice beyond foreground, amber landing lamp behind.', 'Another little stair. Then the passage opened wide.',None),
('The plateau cave','C0 establishing','Pair at northeast cave arrival, small against broad safe terrace. West mother, north defender, east light panel glimpse; entry remains visible.', 'They stood on a broad stone floor inside the hill. Great painted pictures curved around them.',None),
('Where the light comes from','C5 ceiling/shaft','Looking up along oblique southwest shaft; actual blue sky patch and stone lip, dust/light cone. Pair optional lower edge look at shaft.', '“Sunlight!” said PinPin. Far above, a crack in the hillside let the day come in. Wall lamps warmed the darker corners.',None),
('Old sacred pictures','C0 lower mural survey','Pair look together at mural borders, not viewer. Flat paintings visibly distinct from living cast.', '“These are sacred stories,” said the Elder. “Stories some forest families treasure.”',None),
('What does sacred mean?','C1D question','PinPin right looks up/left directly at Elder left; Elder eyes child. Mother mural edge in background.', '“Sacred?” “Very precious to them. Something they treat with special care.”',None),
('What is religion?','C1D answer','Elder left looks into child eyes right; child listens. Small prayer/seed ledge visible by mural.', '“They believe in gods and spirits,” said the Elder. “Their stories, prayers and ways of giving thanks are part of their religion. Other families may believe different things.”',None),
('The Mother of Life','C1 mural full','Painted pregnant HUMAN WOMAN in full robe, visible belly, hand resting there; cradle/baby and grain emblems below. Pair foreground gaze at image.', 'PinPin looked at a woman with a round belly. “Is there a baby inside?” “Yes. She is the Mother of Life in these stories.”',None),
('New life','C1D close child question','Child right turns from mural toward Elder left; eye contact. Pregnant painting remains visible behind them.', '“Is she a goddess?” “Yes. A goddess of fertility. That means new life: babies being born, and seeds growing into food.”',None),
('Baby and grain','Mural detail insert','Flat painted cradle with cared-for baby and sprouting grain beneath same mother robe hem; no new live baby in room.', 'PinPin found the painted baby. Then he found the tiny green shoots. “Both need looking after,” he said.',None),
('Prayer and thanks','C1 ledge medium','Elder left points with one forepaw toward old seed bowl/flower on ledge; PinPin right looks at exact bowl. Neither compelled to pray.', '“Some families bring seeds here,” said the Elder. “They pray. They ask the goddess for help, or say thank you.”',None),
('Care continues outside the story','C1D two-shot','Both turn toward each other, away from ledge. PinPin right listening to Elder left; warm, no sermon pose.', '“And then?” asked PinPin. “Then they go home and care for their babies and their gardens.”',None),
('The Shield Keeper','C2 north mural full','Strong adult HUMAN MAN painted in bronze armor/red cloak; shield before tiny families, sheathed sword; blue storm outside. Pair small lower-right look up.', 'On the next wall stood a strong man with a great shield. Behind him, families huddled together.',None),
('A god of war','C2D question two-shot','PinPin right looks left at Elder; Elder left meets gaze. Shield mural cropped behind, not replacing listener.', '“Who is he?” “The Shield Keeper. In these stories, he is a god of war.”',None),
('What is war?','C2D reply angle same axis','Elder left lowers head toward child right, both mutual gaze. Warm firm expression, no frightening reenactment.', '“What is war?” “When large groups of people fight one another. It can hurt people and destroy their homes. Here, he stands in the way of harm.”',None),
('What the shield protects','North mural detail','Shield on right blocks cold jagged storm at far right from warm homes and families on left. No death, gore, weapons striking bodies.', '“If the darkness swept everything away, where would the little ones live?” asked PinPin. He looked at the tiny homes behind the shield.',None),
('The child is safe here','C2D reassurance','Child right near Elder left; Elder responds into child’s eyes. Safe lamp and peaceful real cave visible, storm remains flat painting.', '“This is a picture, and you are safe here,” said the Elder. “It tells us why protecting others matters.”',None),
('Strong enough to protect','C2 two-shot shield connection','PinPin right asks Elder left with reciprocal gaze; shield remains background target for following glance.', '“Does he like fighting?” “The best defender wants everyone safe. Being strong is not a reason to hurt someone.”',None),
('Light and darkness','C3 east mural full','Flat gold sun/living tree/shelter contends with blue-black cold storm. Pair foreground looking at picture; actual lamps distinct from painted light.', 'Another picture showed light pushing back a great cold darkness. A little shelter glowed between them.',None),
('Is night bad?','C3D child reaction','PinPin right faces Elder left, eyes meet; dark mural behind kept calm and visibly painted.', '“But I like night,” said PinPin. “Mama tucks me in.”',None),
('Restful night and harmful darkness','C3D mentor reply','Elder left smiles toward child right; reciprocal gaze; tiny star border of mural in background.', '“So do I,” said the Elder. “Night gives us rest. The darkness in this story means danger that could take their home away.”',None),
('Many helpers','C4 south frieze survey','Pair move together to south frieze, eyes on painted cooperative families: female builders, male carers, different animals; no future machinery.', 'On the last wall were many small helpers. Some carried wood. Some brought food. Some held babies.',None),
('One shield is not enough','C4D child question','PinPin right looks up at Elder left; Elder meets gaze. A beam carried by two painted animals visible below.', '“Can the Shield Keeper do all those jobs?” “No,” said the Elder. “No one can.”',None),
('A community keeps life safe','C4 detail/action two-shot','Elder left points to two painted animals carrying beam, PinPin right follows paw target; distinct shared attention.', '“A strong arm can hold a shield. Other paws grow food and build warm homes. They need one another.”',None),
('What can I do?','C central bench two-shot','Pair seated at low central bench, Elder left child right meet eyes. Murals soft background, no props multiplying.', '“And my quill?” asked PinPin. “Your gift can help. First, look. Listen. Ask who needs you. You do not have to help all alone.”',None),
('A question inside','C central quiet close','PinPin eyes gently lowered to own paws/back quill reflection not needed; Elder quietly attentive beside him. No magical vision.', 'PinPin was quiet. He thought of the lake, the little plant, and the homes on the map.',None),
('Back to the stair','C6 departure wide','Pair walk northeast to same bottom stair opening. Child slightly ahead, Elder behind. Lamp and mural coordinates unchanged.', '“Shall we go back?” asked the Elder. PinPin nodded. He had more questions now.',None),
('First steps up','T2 ascent','PinPin leads up flight B away from cave; Elder follows within one body length. Eyes on steps. No turned talking faces while climbing.', 'Up they went. One broad step, then the next.',None),
('The familiar landing','T1 ascent landing','Pair stopped on exact same landing; child has turned left toward upper flight; Elder watches child. Same lamp/rail.', 'There was the little lamp again. PinPin turned the corner.',None),
('Through the open door','H3 top threshold','PinPin crosses level top landing through same open plank door into home; Elder one step behind. Desk visible in correct room side.', 'The books and the ink-stained table came back into view. They were in the Elder’s home again.',None),
('The question goes on paper','H1 table writing','Elder left writes; PinPin right watches nib. Cave door CLOSED visible background after narrated closure; no staff inside.', 'The Elder closed the stair door. “What shall I write?” “How can my magic help?” said PinPin.',None),
('Old magic, more to learn','H0 reciprocal at table','Elder left turns from page to child right. Both eye contact; writing feather laid on rest, no extra hand.', '“Your quill carries old magic from our ancestors,” said the Elder. “There is still much to learn. We will take our time.”',None),
('Outside again','E0 threshold exit','PinPin emerges from root arch, Elder follows; staff still rockleft; upright plant/branch right. Pair look at outside path, not dialogue.', 'Outside, the leaves glowed gold. The little plant stood free beside the fern.',None),
('Tomorrow’s hilltop','Empty summit insert','Separate summit oak only, no actors, future lesson not happening now.', '“Tomorrow at dawn,” said the Elder, “meet me by the oak on the hilltop. We will begin with listening.”',26),
('A proper goodbye','E0 reciprocal farewell NEW','PinPin near path right turns face LEFT toward Elder at rootleft. Both visibly meet gaze; warm sunset, no explicit sun disc.', '“At dawn,” said PinPin. “Thank you.” The Elder smiled. “Bring your questions.”',None),
('The path away','Departure wide','PinPin walks toward foreground away from hill; eyes on route/sky. No claim he is looking back at Elder.', 'PinPin set off. He did not know everything yet. But now he knew where to begin.',28),
('The leaf window','Silent leaf arch','Empty sunset leaf window; no actors.', '',29),
('Peek','Silent leaf arch','PinPin peeks through same leaves looking at reader; playful final beat, no partner.', '',30)
]
scenes=[]
for i,(title,camera,action,dialogue,reuse) in enumerate(rows,1):
 s={'id':f'elder-r2-{i:02d}','title':title,'phase':('arrival' if i<=7 else 'small-help' if i<=10 else 'dwelling' if i<=18 else 'descent' if i<=23 else 'sacred-pictures' if i<=45 else 'return'),'camera':camera,'blockingAndEyeline':action,'dialogue_en':dialogue,'imageStatus':'reuse-candidate' if reuse else 'planned-new','priorScene':f'elder-{reuse:02d}' if reuse else None,'proposedSrc':old[reuse-1]['src'] if reuse else None,'sourceKind':'source-adapted' if i<=7 or i>=51 else 'user-authorized-expansion','gate':'not-rendered; awaiting internal story/spatial gate'}
 scenes.append(s)
(p/'shot-plan.json').write_text(json.dumps({'schemaVersion':1,'status':'draft-for-internal-review','revision':2,'id':'elder','sceneCount':len(scenes),'audience':'read aloud to four-year-olds','coordinates':'See bible.md; planning units, not calibrated measurements','scenes':scenes},ensure_ascii=False,indent=2)+'\n')
(p/'dialogue_EN.md').write_text('# Elder revision 02 — English story draft\n\nStatus: internal editorial review; images not yet rendered. Short visual beats are intentional; image count is coverage, not a quota.\n\n'+'\n\n'.join(f'## {i:02d}. {r[0]}\n\n{r[3] or "[Silent picture]"}' for i,r in enumerate(rows,1))+'\n')
print(len(scenes),'scenes;',sum(len(r[3].split()) for r in rows),'English words')
