from pathlib import Path
import json,datetime
p=Path(__file__).parent.resolve(); base=p.parents[3]; assert base.name=='storyboard',base
old=json.loads((p/'../../elder/chapter.json').resolve().read_text()); plan=json.loads((p/'shot-plan.json').read_text()); tr=json.loads((p/'translations.json').read_text());alt={}
for line in (p/'alt.tsv').read_text().splitlines():
 n,ru,en,es=line.split('\t');alt[int(n)]={'ru':ru,'en':en,'es':es}
root='images/chapter-02-expanded/revision-02/';special={12:root+'preproduction/home-v2.png',18:root+'scenes/scene-18-v2.png',24:root+'preproduction/gaze-shared-v2.png',38:root+'scenes/scene-38-v2.png',41:root+'scenes/scene-41-v3.png'}
# This explicit selection file overrides defaults without guessing newest variants.
sel=p/'selected-images.json'
if sel.exists():special.update({int(k):v for k,v in json.loads(sel.read_text()).items()})
d={k:old[k] for k in ['schemaVersion','id','sourceChapter','status','title','cover']};d.update({'revision':2,'productionState':'review-ready','planningDiagram':'floorplan.svg','summary':{'ru':'Пин-Пин впервые приходит к Старейшине, исследует его дом и пещеру священных картин и узнаёт о новой жизни, защите и общих делах.','en':'PinPin visits the Elder’s home and cave of sacred pictures, learning about new life, protection and the work a community shares.','es':'PinPin visita la casa del anciano y la cueva de pinturas sagradas, y descubre la nueva vida, la protección y el trabajo compartido.'},'preproduction':old['preproduction'][:2]})
d['preproduction'][1]['description']='Exterior continuity: root portal, parked staff left, fern/plant right, separate summit oak. Plant state changes during brief rescue.'
for name,title,desc in [('home-v2','The Elder’s furnished home','Corrected right hinges and reachable lowleft pull ring; books, writing table, artifacts, bed and two distinct thresholds.'),('stairs-v3','The connected staircase','Home visible only through upper door; two flights, level turn, fixed lamps and enclosed cave bottom. Illustrated planning reference, exact tread count unverified.'),('murals-v1','The sacred pictures','Original authored forest-tradition iconography: pregnant Mother of Life, male war defender, light and darkness, shared work.'),('cave-v1','Cave master','West life, north defender, east light, northeast stair arrival, southwest actual daylight shaft; north-wall bench.'),('cave-south-v1','Cave reverse / south wall','Community frieze and reversed east/west clues; no new doorway.'),('gaze-shared-v2','Shared attention','Rear three-quarter bodies facing one mural; grounded paws. Conversation uses separate reciprocal views.')]:d['preproduction'].append({'id':name,'title':title,'src':root+'preproduction/'+name+'.png','description':desc})
seq=[('arrival','Дорога к Старейшине','The path to the Elder','El camino al anciano'),('small-help','Маленькая помощь','A small act of help','Una pequeña ayuda'),('dwelling','Дом мудреца','The wise one’s home','La casa del sabio'),('descent','Под холмом','Beneath the hill','Bajo la colina'),('sacred-pictures','Священные картины','The sacred pictures','Las pinturas sagradas'),('return','Обратный путь','The way back','El regreso')]
d['sequences']=[{'id':s[0],'title':dict(zip(['ru','en','es'],s[1:])),'purpose':'Continuous first mentor visit; see detailed shot plan.'} for s in seq];d['scenes']=[];pending=[]
for n,s in enumerate(plan['scenes'],1):
 reused=bool(s['priorScene']); prior=next((v for v in old['scenes'] if v['id']==s['priorScene']),None)
 src=special.get(n,s['proposedSrc'] or root+f'scenes/scene-{n:02d}-v1.png');f=base/src;record={}
 if f.with_suffix('.json').exists():record=json.loads(f.with_suffix('.json').read_text())
 review=record.get('review') or ('Re-inspected in revision02 all30 EYELINE-AUDIT.md; selected for the stated action/gaze.' if reused else 'Pending full image inspection/selection.')
 if not reused and (not f.exists() or not record.get('review')):pending.append(n)
 text={'en':[s['dialogue_en']] if s['dialogue_en'] else [],'ru':[tr[s['id']]['ru']] if tr[s['id']]['ru'] else [],'es':[tr[s['id']]['es']] if tr[s['id']]['es'] else []}
 blocks=[1] if n<=3 else [2] if n==4 else [3] if n==5 else [4] if n==6 else [5,6] if n<=10 else [10] if n==51 else [12] if n in (53,54) else [13] if n>=55 else [6]
 scene={'id':s['id'],'sequence':s['phase'],'src':src,'width':record.get('width',1536),'height':record.get('height',1024),'alt':alt[n],'text':text,'source':{'kind':'silent' if n>=56 else 'original' if n<=6 or n>=53 else 'expanded','blocks':blocks,'note':'Original first-visit spine adapted; religious pantheon, home/cave journey and symbolic teaching are user-authorized additions. See source-adaptation-map.md.'},'camera':s['camera'],'continuity':s['blockingAndEyeline'],'review':review,'reused':reused}
 if 8<=n<=50 or n==52:
  scene['source']={'kind':'new','blocks':[],'note':'New user-authorized adaptation scene. Religion, deity iconography, home/cave geography and dialogue are not present in original chapter02. See source-adaptation-map.md for later-source thematic support.'}
  if 24<=n<=45:scene['source']['thematicSupport']=['Chapter02 block6 responsibility (zero-based), not evidence of deities/religion in that passage.','Later chapters11–12 light/winter myth and17–25 communal protection; exact cave/murals/pantheon newly authored.']
 if n==7:scene['source']={'kind':'expanded','blocks':[5,6,8,9,10],'note':'Lake/quill, responsible power and origin question adapted into one short exchange and new invitation.'}
 if n==54:scene['source']={'kind':'expanded','blocks':[12,13],'note':'Added reciprocal goodbye after original future-dawn promise.'}
 if prior:scene.update({'before':prior['src'],'beforeText':prior['text'],'beforeNote':'Earlier proposal passage; selected image retained after actual revision eyeline audit.'})
 d['scenes'].append(scene)
d['editorialNotes']=['Second proposal:57 visual beats, brief concrete exchanges for age-four read-aloud. No image quota.','The three-image plant rescue is a small act within a fuller mentor visit.','Religious paintings and cave route are explicitly commissioned new adaptation, not recovered chapter02 source.','Human deity figures remain flat paintings; Elder identity and later story reveals remain concealed.','Planning coordinates and dimensions are qualitative art direction, not a calibrated reconstruction.','English/Russian/Spanish narration and all selected images complete; creator full-image and ordered sequence reviews passed. Root browser review is a separate gate.']
d['continuityNotes']=['First visit the day after the lake; next dawn lesson remains promised, not shown.','Exterior staff parked left; freed plant and moved twig stay right after rescue.','Home → inner door → two stair flights/turn → cave plateau → same route up → home → exterior.','Murals fixed west/north/east/south; sky shaft southwest; ordinary night distinguished from destructive darkness in sacred story.']
(p/'chapter.json').write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'scenes':len(d['scenes']),'pendingNewImages':pending}))
